### ISSUE TITLE
US01-F01-SP01: ユーザへのシステムの提供形式を決定する

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#1]

**Comment by ryoki1118** [comment]
RedmineのWikiに記載.
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/04%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E5%8B%95%E4%BD%9C%E7%92%B0%E5%A2%83

**Comment by Altairzym** [comment]
利用者の方でMysqlをインストールしなくてもいいですか？

**Comment by ryoki1118** [comment]
利用者の環境設定の話は入れてないね。
動作保証環境を構築してもらう必要はある。
その話を少し追記します。

**Comment by ryoki1118** [comment]
あ、ごめん。
環境設定の話はUS01-F01-SP02で決めるから, MySQLとRailsのインストールの話はここじゃないかな。

**Comment by yaginuuu** [comment]
おｋ．

**Comment by Altairzym** [comment]
了解！
