### ISSUE TITLE
US01-F03-SP08: 開発環境を作成する(柳沼) 0.5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#10]
## やったこと
- [x] mysqlのバージョンをあげる

![image](https://cloud.githubusercontent.com/assets/3440182/9328319/cfef57ca-45e2-11e5-87ba-619800a95582.png)

**Comment by yaginuuu** [comment]
レビュお願い致しますー。

**Comment by Altairzym** [comment]
Wikiに書いてある内容と同じ、問題ない

**Comment by ryoki1118** [comment]
RubyGemsはアップデートできない？

**Comment by yaginuuu** [comment]
@ryoki1118 
やってみますー

**Comment by yaginuuu** [comment]
![image](https://cloud.githubusercontent.com/assets/3440182/9330537/fbae6984-45f4-11e5-9c49-37ace4ba61aa.png)
アップデートしましたー。

**Comment by ryoki1118** [comment]
おっけーです
