### ISSUE TITLE
チケットの変更をRedmineに更新する 2.5ｈ

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#105]
もう更新しましたので、ご確認ください。
http://vibi-redmine.herokuapp.com/projects/vibi/issues
また、チケットのトラッカーを全部Zenhubのラベルに一致しましたので、ご確認ください。
http://vibi-redmine.herokuapp.com/projects/vibi/issues?c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=%2A&page=1&per_page=100&set_filter=1&utf8=%E2%9C%93

**Comment by ryoki1118** [comment]
OKです

**Comment by yaginuuu** [comment]
okですー！
