### ISSUE TITLE
US01-F03-SP09: 開発環境を作成する(孫)

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#11]

**Comment by sjc1209** [comment]
![qq 20150819153802](https://cloud.githubusercontent.com/assets/7754274/9350293/33d117ae-468a-11e5-946c-ed744f60b877.png)

**Comment by sjc1209** [comment]
gemを「gem update」で更新しましたが、また2.4.5になってるが。

**Comment by ryoki1118** [comment]
$ gem update --system 2.4.8
でやってみて

**Comment by Altairzym** [comment]
mysqlは大丈夫ですが、gemの方バージョンみんな一致したほうがいい

**Comment by sjc1209** [comment]
![qq 20150819184407](https://cloud.githubusercontent.com/assets/7754274/9353465/77185e14-46a3-11e5-83d9-5de7026db56b.png)

**Comment by sjc1209** [comment]
はい、OKです。これで、closeにするか。

**Comment by Altairzym** [comment]
問題なければcloseしてもいいです、redmineの方も

**Comment by yaginuuu** [comment]
えっと、レビュー2人以上！ってことなので、一民がレビューしたからといってclosedできないですよー。

**Comment by ryoki1118** [comment]
おっけーです
