### ISSUE TITLE
データベースの構成を修正する

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#110]
各テーブルの依存関係に問題があるため、修正したい。
例: 「Redmine認証テーブル」にシステムの「ユーザ登録ID」が含まれている。
その他、全体の修正が必要ありそう。

**Comment by yaginuuu** [comment]
@ryoki1118 
developersとprojectsのカラムが少ないことは把握してたｗ
けど, 依存関係に問題あるかな？？
