### ISSUE TITLE
データベースのカラム名に間違いがある 2.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#111]
## やること
- redmine_keysテーブルのカラム修正  
× ticket_repositoty_id  
○ ticket_repository_id

<img width="480" alt="2015-08-27 11 30 03" src="https://cloud.githubusercontent.com/assets/6702920/9511219/38e2dc0c-4caf-11e5-82bc-a676c0e65244.png">

- developersテーブルのカラム修正
adressカラム追加

- projectsテーブルのカラム修正
t.integer :version_repository_id
t.integer :ticket_repository_id
t.time :project_start_date
t.time :project_end_date
追加

#112

**Comment by yaginuuu** [comment]
うわー。

DB関連もろもろ早急にpushします。

**Comment by ryoki1118** [comment]
クローズしてよいよ
