### ISSUE TITLE
ER図を修正する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#117]
## やること
構成管理ツール情報をDBに格納するためにDB構成を変更
![image](https://cloud.githubusercontent.com/assets/3440182/9545386/66a2bd0e-4dc4-11e5-8cac-36813d736aa2.png)

- Gitリポジトリ情報テーブル追加
- Gitリポジトリ :  Gitリポジトリ情報 = 1 : nの関連を追加
- Gitリポジトリ情報 : 開発者 = n : 1の関連を追加

**Comment by yaginuuu** [comment]
@ViBii/owners 
これで異論なければ変更します

**Comment by ryoki1118** [comment]
遅くなりました
これでOKです。

**Comment by yaginuuu** [comment]
コレで構成します.

**Comment by yaginuuu** [comment]
@ViBii/owners 
ごめん。
プロジェクトテーブルとGitリポジトリテーブル・Redmineリポジトリテーブルの関連って逆じゃない？

**Comment by yaginuuu** [comment]
なんかわかんなくなってきた…

**Comment by yaginuuu** [comment]
@ryoki1118 
んーこれでできそうだけど、いいっかこれで。。

**Comment by ryoki1118** [comment]
@yaginuuu いや、これでいいんでない？
できなかったらまた考えよう

**Comment by yaginuuu** [comment]
おｋ
