### ISSUE TITLE
US01-F03-SP10: 開発環境を作成する(一民)

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#12]

**Comment by Altairzym** [comment]
MySQLを導入する

**Comment by Altairzym** [comment]
Mysqlを導入した。バージョンは14.14です。

**Comment by Altairzym** [comment]
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install mysql-server-5.6
三つのコマンドを入力してから、ubuntu上のMysqlバージョンは5.6.19になった、Redmineの方のWiKiに書いてある5.6.26とは違い、これで大丈夫なのかな。。。

**Comment by yaginuuu** [comment]
そんなに重要じゃないような気がするので、
mysql入っていればいいと思います.
柳沼確認しましたー。

**Comment by Altairzym** [comment]
![qq 20150818204231](https://cloud.githubusercontent.com/assets/7775369/9329106/badde746-45e9-11e5-8dcb-097dee58564c.png)
とりあえず、こんな感じです

**Comment by ryoki1118** [comment]
MySQL5.6なら許容範囲ってことでいいでしょう。

**Comment by Altairzym** [comment]
了解です、じゃあこのissueをcloseします
