### ISSUE TITLE
US02-F02-SP01: 構成管理ツールを利用したメトリクスと導出方法の決定 10h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#138]
### Done:
- [x] GitHub APIから取れるデータを把握する
- [x] DropBox上のMetrixListの内容に合わせて、第二スプリントのメトリクスを検討する

### 可視化項目：　開発者の会話力
- 開発者間のコミュニケーションが定量的にグラフで表現できる
- 実装した機能のイメージは #140 を見てください

### issuesのcommentから開発者のissueに対するcommentの回数が統計できる

- このアドレスにアクセスすれば、現時点のIssues情報がもらえる
```
https://api.github.com/repos/ViBii/mitemiru/issues
```
このアドレスの後ろ、
```
/issues?state=all&labels=SUPPORT
```
の様な様々な検索条件が追加できる。

- あるissueに対するcommentsの表示したい場合、
```
https://api.github.com/repos/ViBii/mitemiru/issues/138/comments
```

今考えできるのは、issuesの中の"comments"属性で判断し、各issueをループし、"comments"が0ではない場合、そのissueのcommentsを見て、特定開発者のcommentの回数を計算する。
しかし、そのuserからcomment履歴を見たい場合、APIから直接取る方法がなさそうです

**Comment by Altairzym** [comment]
https://api.github.com/repos/ViBii/mitemiru/pulls
このアドレスにアクセスすれば、現時点のpullrequestのデータがもらえる、この後、pullrequestについて取れる情報を第二スプリントのメトリクスにいれるつもり

**Comment by Altairzym** [comment]
https://api.github.com/repos/ViBii/mitemiru/issues
このアドレスにアクセスすれば、現時点のIssues情報がもらえる、しかし各Issueに対するcommentがなさそうです

**Comment by Altairzym** [comment]
https://api.github.com/repos/ViBii/mitemiru/collaborators
で開発者を表示したい時、権限問題が発生し、どう解決するか調べる中。。。

**Comment by yaginuuu** [comment]
@Altairzym 
コメント遅くなった！
GitHubAPIで取得できるデータの把握は
Doneの定義には含まなくていいんじゃない？
ここでは, 「もっとどの項目を可視化するか」っていうことを考えて欲しい！
でも、今やっていることも無駄ではないです！！

**Comment by ryoki1118** [comment]
なんか色々情報を取得する方法は書いてあるけど、結局メトリクスは何？

**Comment by Altairzym** [comment]
あ、忘れた。もう修正した、Issueのcommentsからある開発者のcomment回数が統計できる

**Comment by Altairzym** [comment]
commitsの部分も調べましたけど、デフォルトはmaster上のcommitsしか取れない
```
https://api.github.com/repos/ViBii/mitemiru/commits
```

他のブランチの中のcommitを取りたい場合、
```
https://api.github.com/repos/ViBii/mitemiru/commits/showAlldeveloper
```
の様な、後ろに、ブランチ名を追加する必要がある、しかしどうやってブランチ名を検索するか、まだ分からない

**Comment by yaginuuu** [comment]
@Altairzym 
コメント回数から発言力を計るってことかな？？
発言力かああああ。
それはいいとして、第2スプリントではメトリクス2つくらい対象にしたい！

**Comment by ryoki1118** [comment]
コメントの回数を数えてグラフ化するってこと？
このままだとコミット数と対して変わらない気もするなぁ...
発言の中身とか関連について触れられると嬉しいかなー

**Comment by Altairzym** [comment]
@yaginuuu そうですね、発言力の様な感じです

**Comment by Altairzym** [comment]
@ryoki1118 そうですね、コメント回数をグラフ化にします。
どうやってコメントの中身を分析するかな。。。文字列分析ツールを導入するの話し？

**Comment by ryoki1118** [comment]
@Altairzym 自然言語処理まで入れると重すぎるよね
@Altairzymみたいな誰に向けての発言かとかいう情報取ってきて、開発者同士の紐付けみたいなことできないかな？

イメージはこんな感じ。会話が多い人同士だと線が太くなるとか。
http://bl.ocks.org/mbostock/4062045

**Comment by Altairzym** [comment]
@ryoki1118 うわっ！！！！

**Comment by Altairzym** [comment]
@ryoki1118 それが実現できると思う、
先ずはcomments属性の値は0ではないissuesを探して、その中から各issueの担当者の名前が取れる。そして、ssueのcommentsの中に入って、そのissue担当者以外の人のcommentは全部そのissueの担当者への会話と考えれば、開発者間の線が太くなる。

**Comment by ryoki1118** [comment]
そんな感じでいいと思う
需要があるかは日立に聞いたりしないとわからんけど。

**Comment by sjc1209** [comment]
コメント数から開発者の「主体性」が見えて、もう一つのメトリクスがあったらいいと思う。

**Comment by ryoki1118** [comment]
> 開発者の性格が推測できる
どうやって推測するの？

**Comment by ryoki1118** [comment]
これレビュー待ちだよね？
決定でいいと思う

**Comment by Altairzym** [comment]
了解です

**Comment by sjc1209** [comment]
「開発者の会話力」つまり人のコミュニケーション能力を定量化したい場合、Github上のIssueのコメント数だけから判断するのがちょっと妥当ではないと思うか、Issueのコメント数が多いほど、プロジェクトへの関心が高い、Issueに対し自分なりの発想やアイディアがあると思いますが、これとコミュニケーション能力ちょっと違うと思う。

**Comment by yaginuuu** [comment]
@Altairzym 
孫くんの指摘に答えよう！！

**Comment by Altairzym** [comment]
@sjc1209 しかしgithub上のコミュニケーションはcommentで表現するしかないと思うので、最後、commentの数=コミュニケーション力　と考えた

**Comment by Altairzym** [comment]
@sjc1209 Sorry,I can't answer your question ,Oh my God!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sjc1209** [comment]
えっと、














えっと、コメント数は「主体性」と関係があるという考えはどうですか。DropboxのMetrixListの中に書いたように、「主体性」は「各開発者が自発的に行動した履歴を定量的に計測する.」で、コメントは開発者がプロジェクトに対し、自発的な行動ですね。これは妥当だと思う。

**Comment by Altairzym** [comment]
@sjc1209 いいと思う！
