### ISSUE TITLE
US02-F02-SP02: チケット管理ツールを利用したメトリクスと導出方法の決定 11h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#139]
## Done definition.
2人以上のレビューで承認してもらうこと。

## What I did.
構成管理ツール(Redmine)上の情報を利用したメトリクスと導出方法の決定。

#### 可視化項目(ハイブリッド型)
1. 生産性:
 - チケットの見積もり工数 [h]と実績工数 [h]を比較できる形式でグラフ化する
2. 役割
 - トラッカーごとに生産性を表示することで、担当する役割(トラッカー)の傾向を把握できる

**グラフイメージ(#163で要検討)**
<img width="405" alt="2015-09-11 12 11 50" src="https://cloud.githubusercontent.com/assets/6702920/9806346/7052f02a-587e-11e5-8340-3443e9829567.png">

#### 導出方法
1. Redmineから各担当者のチケット情報を収集
2. Redmineのチケットに登録されている「予定工数」「作業時間の記録」をトラッカーごとに算出
3. グラフ化して表示する

**Comment by ryoki1118** [comment]
こんな感じで考えてみたけど、イマイチしっくりこないので意見欲しいです。

**Comment by yaginuuu** [comment]
>チケットの予定工数と実績工数の比較

トラッカーごとにこれやるのかどうかだなあ。
チケットごとにやってもいいかもしれないと思った。

**Comment by ryoki1118** [comment]
@yaginuuu チケットごとってどういうイメージ？

**Comment by yaginuuu** [comment]
あーよく見たらそうなってた。

ごめん。自分でチケットごととか言っててなんだけど…
どんなトラッカーが生産性高いか見分けるってことで、
そいつがどんなチケットで力発揮できるからわかるかも。。
例えば、バグのチケットは工数増えたけど、テストのチケットは予定より少ない工数でやってるから、こいつはテスト得意なんだ的な。

**Comment by ryoki1118** [comment]
@yaginuuu その考えはあった。Redmineだと予定工数[h] と作業時間[h]っていう欄があるから、そこから時間にどれくらい差があるか調べて、トラッカーと組み合わせれば実現できるね。あとは開始日と期日の情報も使いたいけど、これは予定なのか実績なのかは人によって使い方違うから扱いにくいかなぁ。

**Comment by yaginuuu** [comment]
せやな。
だから、チケットごとにガントチャートでやるのもありだけど、
トラッカーごとに工数と作業時間に着目するのありやな。

**Comment by ryoki1118** [comment]
@yaginuuu こんな感じ？
でもなんかパッとしないよなぁ。
<img width="405" alt="2015-09-11 12 11 50" src="https://cloud.githubusercontent.com/assets/6702920/9806346/7052f02a-587e-11e5-8340-3443e9829567.png">

**Comment by sjc1209** [comment]
トラッカーごとで集計すると、「生産性」だけではなくて、「バグの発見数・解消数」の面からも評価できるね。

**Comment by Altairzym** [comment]
これがあれば、実際の工数と予定工数の違いが分かり、該当開発者の傾向（例えばいつも予想より時間かかるとか）推測できるね、そしてどんなチケットが得意か（予想時間より早い）、どんなチケットが下手か多分グラフを見ると、分かると思う

**Comment by ryoki1118** [comment]
記述整理しました。
とりあえずこれで決定していいですかー？

**Comment by yaginuuu** [comment]
確認しますた！

**Comment by Altairzym** [comment]
いいと思います！
