### ISSUE TITLE
US02-F02-SP03: 構成管理ツールのメトリクス可視化方法(グラフ化)を決定する 4.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#140]
### 機能のイメージ
![image](https://cloud.githubusercontent.com/assets/7775369/9809176/01629e86-58a1-11e5-8fea-efdeaea0faa2.png)
- 各ポイントはgithubリポジトリの中の開発者である
- 開発者間の線はコミュニケーションがあるかどうか表示できる
- 線の太さは両者の会話（issueへコメント）の頻度が表示できる

### ToDo
- [x] 大木君提案してくれたグラフとの連携方法を考える

#### 参考：D3.jsグラフサンプル
```
http://bl.ocks.org/mbostock/4062045
```

#### DONE:このグラフの使用方法とパラメータの説明
- jsとcss変更しない
- jsonデータを用意する
  - jsonデータの中のパラメータ
    - nodes Array:
      - name:開発者名
      - group:グラフ中の各ポイントの色、同じgroupだったら、色が同じにする(各開発者を区別するため、一致にしないほうがいい)
    - links Array:
      - source:nodes Arrayの中の各データのlocation(0から)
      - target:  接続先の番号(自分と接続すると、jsエラーが出てくる)
      - value:   は接続した二つのpointの間の線の太さ(つまりcommentsの数が表示できる)

**Comment by Altairzym** [comment]
このグラフ、前導入したグラフの様な感じで、現在のプロジェクトの中に導入する必要がある？

**Comment by ryoki1118** [comment]
>group:グラフ中の各ポイントの色、同じgroupだったら、色が同じにする(各開発者を区別するため、一致にしないほうがいい)

groupってなに？

> このグラフ、前導入したグラフの様な感じで、現在のプロジェクトの中に導入する必要がある？

それは実装の話だからここじゃなくていいと思う

**Comment by Altairzym** [comment]
@ryoki1118 はグラフの中の点の色です、同じgroupの点は色が同じ。例えば、グラフの中、五つ点があって、各点のgroup属性が1~5に設定すれば、グラフ中の点は五つ色がある、つまりgroup属性で、色がコントロールできる

**Comment by ryoki1118** [comment]
あーgroupって概念はわかるんだけど、
> (各開発者を区別するため、一致にしないほうがいい)

これの意味がよくわかんない

**Comment by Altairzym** [comment]
@ryoki1118 ただ各開発者を色分けになって、見やすいと考えた。。。

**Comment by ryoki1118** [comment]
あ、何人かの開発者でグループを作るわけじゃないってことね

**Comment by Altairzym** [comment]
@ryoki1118 そうですね。。そんな感じです

**Comment by ryoki1118** [comment]
これでいいと思いますー

**Comment by Altairzym** [comment]
@ryoki1118 ありがとう！

**Comment by sjc1209** [comment]
えっと、どんな基準に沿って、各開発者を色でわれたんですか。同じプロジェクトに所属する開発者が同じ色ですか。

**Comment by Altairzym** [comment]
@sjc1209 基準は特にないです、見やすい、理解し易いの設定方法が最優先

**Comment by sjc1209** [comment]
基準がないと、適度に開発者を色付けて、分けて、逆に「どうしてこれらの開発者は赤、そちらの開発者が青」と質問があって、理解に難しくなると思う。色付けば、つける基準や理由が明確すればいいと思う。

**Comment by yaginuuu** [comment]
@Altairzym 
孫くんの指摘に答えよう！！

**Comment by Altairzym** [comment]
@sjc1209 実際はこの図はどうして色分け機能があるか解答できない。。。サンプルの中のjson形式はそのような感じでした。。。その部分を修正すると、多分js,css部分も修正しないといけないです。。。

**Comment by Altairzym** [comment]
@sjc1209 あ、違う違う、多分必要があると思う！例えば、ある開発者を選択した時、この色分け機能でその開発者だけグラフの中に強調表示することができる、多分強調表示の時使うと思う
