### ISSUE TITLE
US03-F01-SP01: Redmineの認証情報入力フォームを作成する 1.5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#141]
### DefDone
Redmine認証フォームを作成する

### HowTo
こんな感じで作成
![image](https://cloud.githubusercontent.com/assets/3440182/9800554/7ccac7aa-5848-11e5-85c1-50633d006b44.png)

### PullRequestLink
#160

**Comment by Altairzym** [comment]
私の方問題ないです

**Comment by sjc1209** [comment]
OKです。
