### ISSUE TITLE
US03-F02-SP01: Redmineからプロジェクト名と所属開発者名を取得する 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#144]
### DefDone
- [x] 選択した開発者の所属プロジェクト名を取得
- [x] 選択した開発者の所属プロジェクトの開発者名を取得

![image](https://cloud.githubusercontent.com/assets/3440182/10070978/263a954c-62f1-11e5-8729-9544a5d890fd.png)

### PullRequestLink
#187

**Comment by ryoki1118** [comment]
Done?

**Comment by yaginuuu** [comment]
これ、Doneなので、プルリク見て判断してほしいですー。
レビューできます？？

**Comment by yaginuuu** [comment]
これclosedしますね。

**Comment by sjc1209** [comment]
OKです。
