### ISSUE TITLE
US03-F02-SP02: 選択された開発者が所属するプロジェクトを一覧表示する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#145]
### DefDone
- [x] 選択した開発者の所属プロジェクトを一覧表示

![image](https://cloud.githubusercontent.com/assets/3440182/10070978/263a954c-62f1-11e5-8729-9544a5d890fd.png)

### PullRequestLink
#187

**Comment by sjc1209** [comment]
今の段階ではまだ完成してないですよね。

**Comment by yaginuuu** [comment]
@ViBii/owners 
これ、Doneなので、プルリク見て判断してほしいですー。
レビューできます？？

**Comment by yaginuuu** [comment]
@ViBii/owners 
完成してます。

**Comment by yaginuuu** [comment]
@ViBii/owners 
http://test-vibi-redmine.herokuapp.com/
の方で確認してもらえるとよくわかると思います。
misakaさんはプロジェクト1とプロジェクト3に所属しています。

**Comment by yaginuuu** [comment]
これclosedしますね。
誰か応答お願いします。

**Comment by sjc1209** [comment]
OKです。

**Comment by Altairzym** [comment]
問題ないです
