### ISSUE TITLE
US03-F03-SP01: 各プロジェクトに対応するGithubの認証情報入力フォームを作成する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#147]
### DefDone
- [x] 選択した開発者の所属プロジェクトに対応するGitHub認証情報入力フォームを作成

![image](https://cloud.githubusercontent.com/assets/3440182/10070978/263a954c-62f1-11e5-8729-9544a5d890fd.png)

### PullRequestLink
#187

**Comment by yaginuuu** [comment]
これ、Doneなので、プルリク見て判断してほしいですー。
レビューできます？？

**Comment by yaginuuu** [comment]
これclosedしますね。
誰か応答お願いします。

**Comment by Altairzym** [comment]
問題ないです

**Comment by sjc1209** [comment]
OKです。
