### ISSUE TITLE
US03-F03-SP02: 関連情報をデータベースに登録する 12.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#148]
### DefDone
- 関連情報を登録する(関連テーブル)
    - [x] assign_logs
    - [x] developers
    - [x] projects
    - [x] redmine_keys
    - [x] ticket_repositories
    - [x] github_keys
    - [x] version_repositories

### Overview
登録フローはひとまず大枠はできました.  
![Alt Text](https://i.gyazo.com/c48efcd0e75c38e8c5869db7cf53f18e.gif)

- 仕様
    - 重複について
        - プロジェクトはプロジェクト名を重複チェック
        - 開発者はアドレスを重複チェック
        - ticket_repositories, version_repositoriesについてはurlを重複チェック
    - 重複チェック, 開発者が所属するプロジェクトを参照するためなどに少々時間がかかる
    - バリデーションについて
        - まだ実装していない
        - 現在のところ, 重複しているものについては登録はされないが, 空白チェックはしていない.
        - またURLチェックや, api認証チェックも必要

### Test
- 関連情報テーブルに登録されていることを確認しました.

### PullRequestLink
#191

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしますー。
ブランチはまだマージしなくていいです〜。

**Comment by ryoki1118** [comment]
> ticket_repositories, version_repositoriesについてはurlを重複チェック

これってデータベースに既に登録されているURLと重複チェックするってこと？

**Comment by yaginuuu** [comment]
@ryoki1118 
そうです！！

**Comment by yaginuuu** [comment]
どうしても再現できないんだよなー

これ一度マージして、BUGチケットとして作っていい？？

とりあえず、他のチケットやりたい。

**Comment by ryoki1118** [comment]
@yaginuuu 既に登録されているプロジェクトだと、登録情報は更新されない仕様ってことでよいの？初期登録時のデータを上書きできないみたいだけど。

**Comment by ryoki1118** [comment]
@yaginuuu こっちは登録時エラーはなかったけど、一民のやつはバグチケットで出して他のチケット進めていいと思う。

**Comment by yaginuuu** [comment]
@ryoki1118 
そうそう。
それ治そうと思ってた。
それは、一民のやつとは別なんだよなあ。

別チケットきりますね。

**Comment by yaginuuu** [comment]
#195 別チケットきりました。

**Comment by ryoki1118** [comment]
マージしたのでクローズおっけーかな？

**Comment by yaginuuu** [comment]
あざすー
