### ISSUE TITLE
US01-F04-SP01: ペルソナを作成する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#15]
## Done definition.
2人以上のレビューで承認してもらうこと。

## What I did.
日立をモデルとしたペルソナを追加しました。

## How to check.
RedmineのWikiを参照してください。
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/%E3%83%9A%E3%83%AB%E3%82%BD%E3%83%8A

**Comment by yaginuuu** [comment]
@ryoki1118 
ヒアリング内容反映されてて、いいと思います。

**Comment by yaginuuu** [comment]
@Altairzym @sjc1209 
これレビューしちゃいなよ。
あと20分で今日終わる。

**Comment by Altairzym** [comment]
いいと思います！

**Comment by ryoki1118** [comment]
クローズしまーす
