### ISSUE TITLE
JSの読み込みができていない問題 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#156]
### 問題
- ヘッダーのリンクから遷移するとJSが読み込まれない

### 改善点
#160 
- リンクではなく、JSの方で制御
![Alt Text](https://i.gyazo.com/24019067d1b554ff251f0ddc6e0982fa.gif)

**Comment by ryoki1118** [comment]
もしかしたら、ページ内でJSファイルをIncludeすれば解決するかも？

**Comment by yaginuuu** [comment]
#160 こちらで解決済みです！

**Comment by yaginuuu** [comment]
closedしていいかな？？？

**Comment by ryoki1118** [comment]
mergeされてるならいいと思う
