### ISSUE TITLE
US01-F04-SP02: システムの画面遷移図を作成する 5.0h+5.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#16]
### Doneの定義
- [x] Cacooで遷移図作成
- [x] チームレビュー

### HowTo
一民の作成の画面遷移図＆大木作成のシステム構成図を見ながら作成した.
Dropbox/00各種ドキュメント/05図/画面遷移図/画面遷移図.png

### 画面遷移図
![default](https://cloud.githubusercontent.com/assets/3440182/9771107/dbb84f60-576e-11e5-8c51-7d3a326b9d2b.png)

### 前担当者
一民

**Comment by Altairzym** [comment]
- PowerPointで画面遷移図かつペーパープロトタイプ作る
- 後チームミーティングする時討論する
- 修正する

**Comment by yaginuuu** [comment]
画面遷移図作るときのなんかいいツールないかなー。
パワポはやめたほうがいいかも。

**Comment by Altairzym** [comment]
XMindでできる？

**Comment by yaginuuu** [comment]
あーできるかも！

**Comment by Altairzym** [comment]
明日やってみるわ！

**Comment by yaginuuu** [comment]
:+1:

**Comment by yaginuuu** [comment]
@Altairzym 
こっちにもxmindでつくってますー。ってことを書いておこう！！

**Comment by Altairzym** [comment]
一応、こんな感じで作ったが、この後、みんなと相談する必要がある
![image](https://cloud.githubusercontent.com/assets/7775369/9413725/aca5304e-486e-11e5-8704-41ed3b126767.png)

**Comment by Altairzym** [comment]
ごめん、図が小さいですけど、dropboxの中に保存した、場所は
![image](https://cloud.githubusercontent.com/assets/7775369/9413764/fb03e154-486e-11e5-81ad-a75a71013287.png)

**Comment by ryoki1118** [comment]
・新規ユーザ画面 → 新規ユーザ登録画面
・開発者の成長過程表示とプロジェクト一覧表示って別のものだと考えてたんだけど一緒にするの？

**Comment by Altairzym** [comment]
今日ミーティングする時コメントを参照し、修正した。
場所はdropの中の
![image](https://cloud.githubusercontent.com/assets/7775369/9442256/e9fa917a-4ab5-11e5-9399-ca5d7c4b2bde.png)画面遷移図2.0.xmind

**Comment by Altairzym** [comment]
@ryoki1118 考えたのは、ポートフォリオ画面で複数メトリクスを表示する同時に、履歴プロジェクトリストも表示する、分ける必要があるの？

**Comment by yaginuuu** [comment]
一民はユーザ(評価する人)が最初にどんな**プロジェクト**があるかを見たいと考えたということなんだろうけど、評価する人ってさ、どんな**人**がいるかを見たいと思うと思う。。(これはみんなに聞きたい)

画面遷移図って難しくてさ、機能レベルじゃないから、たとえば開発者登録画面でもそっからいろいろあると思うし(確認画面やら登録結果画面やら)、今考えるの難しいってことが見て取れるｗ

**Comment by Altairzym** [comment]
@yaginuuu そうですね。。。確かに、実は登録結果画面とか自分の考えとしては、登録画面の「登録」と言うボタンをクリックしてから、ただ「登録成功」と言うメッセージが画面からpopupして、そのあと、画面が自動的に前に画面に遷移する

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いします。
みんなの意見聞きたいです。

**Comment by ryoki1118** [comment]
- ログイン後のポートフォリオ機能トップ画面って画面1のこと？
基本的にJSで動的にページ変えるってイメージかね。
これでいいと思うけど、作り始めて違和感でてきたらまた修正加えましょう。

**Comment by Altairzym** [comment]
なるほど、各画面にどんな機能、どんなhtml要素も説明した、いいと思います

**Comment by yaginuuu** [comment]
@ryoki1118 
>ログイン後のポートフォリオ機能トップ画面って画面1のこと？
そうだね！

>作り始めて違和感でてきたらまた修正加えましょう。
みんなでイメージ共有できることが一番大事！

**Comment by yaginuuu** [comment]
@Altairzym 
レビューありがとう！

**Comment by yaginuuu** [comment]
@sjc1209 
機能を実装するときはこの画面遷移図をイメージして作ってもらいたいので、目を当していただきたいです！

**Comment by ryoki1118** [comment]
@yaginuuu ほい
クローズしていいと思いますー

**Comment by yaginuuu** [comment]
@ryoki1118 
ありがとうごぜいます！
