### ISSUE TITLE
DBスキーマをGitHub仕様に変更する 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#161]
### DefDone
- [x] ER図修正
- [x] システムスキーマに反映
 
### HowTo
論理モデル
![image](https://cloud.githubusercontent.com/assets/3440182/9803889/8ce8b0ba-5862-11e5-9bf4-580cf7511945.png)

物理モデル
![image](https://cloud.githubusercontent.com/assets/3440182/9803893/99260ca6-5862-11e5-956a-2e0107ba99da.png)

- 変更点
    - GitHub認証情報テーブル、GitHubアクセス権テーブル追加
    - developers/adress => developers/emailに変更

システム上のテーブル関連
![image](https://cloud.githubusercontent.com/assets/3440182/9826203/7d867060-5913-11e5-882e-fc8848c6d773.png)

### Test
- [x] カラム名確認
- [x] テーブル関連確認

### PullRequestLink
#164

**Comment by yaginuuu** [comment]
@ViBii/owners 
ER図こんな感じにしてみました。。
スキーマ変えすぎてアレだから、ちょっと物理モデルまで(カラム名まで)入念にチェックお願いしまっす！

**Comment by ryoki1118** [comment]
多分問題なし！
ユーザは唯一のGitHubアカウントを持っているってことでいいんだよね？

**Comment by ryoki1118** [comment]
あ、GitHub APIで使う認証情報ってログイン名とパスワードでいいんだっけ？

**Comment by yaginuuu** [comment]
@ryoki1118 
さんきゅ！
これで大丈夫！
だめだったらあとから追加するわ！

とりあえず、コレ以上は大きく変更するのやめたいssunee笑

**Comment by yaginuuu** [comment]
@ryoki1118 
@Altairzym 
レビューの方はerd.pdfファイルを確認して、Testのカラム名と関連に関してチェックして欲しいです！

**Comment by Altairzym** [comment]
migrateフォルダの中のファイルを見ると、カラム名は一致です、問題はなさそうです。。。関連はまだチェックしてないです

**Comment by Altairzym** [comment]
modelsフォルダの中をみると、関連の部分も問題なさそうですね

**Comment by sjc1209** [comment]
カラムは確認しました。OKです。
![qq 20150912142216](https://cloud.githubusercontent.com/assets/7754274/9830018/080c3134-595a-11e5-8f80-6e742da2d534.png)

**Comment by sjc1209** [comment]
![qq 20150912142151](https://cloud.githubusercontent.com/assets/7754274/9830021/221419a2-595a-11e5-821a-e9e15bc7c559.png)
テーブルを確認する時、project has many developers　というところはちょっと気になるが、これは正しいですか。

**Comment by yaginuuu** [comment]
@一民
さんきゅ！

@孫
うん！
assign_logsテーブルを中間テーブルにした多対多の関連を作ってます！

**Comment by sjc1209** [comment]
なるほど、わかりました。じゃOKです。
