### ISSUE TITLE
US02-F02-SP04: チケット管理ツールのメトリクス可視化方法(グラフ化)を決定する 4h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#163]
## Done definition.
2人以上のレビューで承認してもらうこと。

## What I did.
#139のグラフ化方法の決定

**利用するグラフ: Grouped horizontal bar chart**
http://bl.ocks.org/erikvullings/51cc5332439939f1f292

**グラフイメージ**
<img width="405" alt="2015-09-11 12 11 50" src="https://cloud.githubusercontent.com/assets/6702920/9806346/7052f02a-587e-11e5-8340-3443e9829567.png">

加えて、予定工数と実績工数の内訳を比で見られるように累積棒グラフも横に表示する。
![default](https://cloud.githubusercontent.com/assets/6702920/9877286/e588a8c8-5bf6-11e5-95a9-42d747bff53b.jpg)
http://bl.ocks.org/mbostock/3887235

**Comment by ryoki1118** [comment]
@Altairzym これは俺やります。

**Comment by ryoki1118** [comment]
レビューお願いします

**Comment by Altairzym** [comment]
おｋ、問題ないと思う！

**Comment by sjc1209** [comment]
予定工数と実績工数の詳細を円グラフで表示するって書いてあるですが、具体的にはどんなイメージですか。

**Comment by ryoki1118** [comment]
なんだか分かりにくいから、円グラフやめて累積棒グラフにします。

**Comment by sjc1209** [comment]
はい、累積棒グラフはいいと思う。

**Comment by ryoki1118** [comment]
クローズします
