### ISSUE TITLE
US04の項目追加 1h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#166]
## Done definition.
2人以上のレビューで承認してもらうこと。

## What I did.
- [x] US02で新たに決定したメトリクスの実装タスクをチケットとして発行する

#### 旧US
US04: 開発者1人に対して, 1つのプロジェクトでの取り組みを確認したい [10.0pt]
F01: 構成管理ツール(GitHub)リポジトリの参照 [5.0pt]
- SP01: コミット情報を取得する [2.0pt]
- SP02: コミット数を集計し, グラフ化して表示する [3.0pt]

F02: チケット管理ツール(Redmine)リポジトリの参照 [5.0pt]
- SP01: チケット管理ツールリポジトリから, チケット情報を取得する [2.0pt]
- SP02: チケットの担当者ごとにトラッカーを分類し, グラフ化して表示する [3.0pt]

#### 新US
US04: 開発者1人に対して, 1つのプロジェクトでの取り組みを確認したい [20.0pt]
F01: 構成管理ツール(GitHub)リポジトリの参照(コミット情報) [10.0pt]
- SP01: コミット情報を取得する [2.0pt]
- SP02: コミット数を集計し, グラフ化して表示する [3.0pt]
- SP03: Issueのコメント情報を取得する [2.0pt]
- SP04: コメント情報を集計し, グラフ化して表示する [3.0pt]

F02: チケット管理ツール(Redmine)リポジトリの参照 [10.0pt]
- SP01: チケット管理ツールリポジトリから, チケット情報を取得する [2.0pt]
- SP02: チケットの担当者ごとにトラッカーを分類し, グラフ化して表示する [3.0pt]
- SP03: チケットの工数情報を取得する [2.0pt]
- SP04: トラッカーごとに予定工数と実績工数を分類し, グラフ化して表示する [3.0pt]

#### 変更点
F01, F02にそれぞれSP03とSP04を追加

**Comment by Altairzym** [comment]
問題ないと思います！

**Comment by sjc1209** [comment]
OKです。

**Comment by sjc1209** [comment]
Redmineのチケットの更新は今からやります。

**Comment by sjc1209** [comment]
Redmineのチケットも更新しましたので、ご確認ください。
@ryoki1118  @Altairzym  @yaginuuu
