### ISSUE TITLE
データベーススキーマの変更がソースコードに反映されていない 1h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#169]
## Overview
#112 から#161 にデータベーススキーマを変更した際、コーディング済みのControllerやViewで使用されているソースコード内での参照を変更していないため、動作しないページがある。
例: http://0.0.0.0:3000/ticket_repositories/new のリポジトリURL登録時にlogin_nameカラムが存在しないと突っ込まれる。（login_name → login_idに変更したため）

## Done definition.
#170 を1人以上のレビューで承認してもらい、masterブランチにmergeしてもらう。

## What I did.
#170 参照

**Comment by ryoki1118** [comment]
誰も動作確認していなかったんだな...

**Comment by yaginuuu** [comment]
@これ俺なおしとくよー

**Comment by ryoki1118** [comment]
@yaginuuu 
もうやっとるけど

**Comment by yaginuuu** [comment]
あーおｋ

**Comment by ryoki1118** [comment]
@yaginuuu .gitファイルから登録する機能って完全に廃止？

**Comment by yaginuuu** [comment]
@ryoki1118 
廃止！

**Comment by ryoki1118** [comment]
じゃ手つけないで置いておくね
