### ISSUE TITLE
US04-F01-SP04: コメント情報を集計し, グラフ化して表示する 5.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#177]
pullrequest: #193

**Comment by ryoki1118** [comment]
2015/09/24追加
#166 参照

**Comment by Altairzym** [comment]
このチケット、これから私がやります

**Comment by ryoki1118** [comment]
ブランチ消去します

**Comment by Altairzym** [comment]
@ryoki1118  @yaginuuu  @sjc1209 これ、こんな感じでいいですか？

**Comment by ryoki1118** [comment]
プルリクが[WIP]だけど終わったってこと？

現段階での評価だけど、もっとわかりやすいグラフにならない？
各点を大きくして開発者名を入れるとか、線の横にコメント数を表示するとか。
ページ上部のコメントがなくても、グラフを見れば情報がわかるようにしなきゃ意味ないかなぁ。

**Comment by Altairzym** [comment]
@ryoki1118 なるほど。。。

**Comment by Altairzym** [comment]
@ryoki1118 「線の横にコメント数を表示する」と「各点を大きくして開発者名を入れる」全部追加した

**Comment by Altairzym** [comment]
closeします
