### ISSUE TITLE
US01-F04-SP04: ER図を作成する 6.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#18]

**Comment by yaginuuu** [comment]
@ryoki1118 
ER図はrailsでのDB設計にするために@yaginuuuがやるよ〜。

**Comment by ryoki1118** [comment]
RailsでのER図ってなんぞや?
ER図って概念設計のレベルで考えてたんだけど...
参考: http://gihyo.jp/dev/feature/01/database/0001

**Comment by ryoki1118** [comment]
![mitemiru_db](https://cloud.githubusercontent.com/assets/6702920/9412459/cb07ac22-4866-11e5-8786-5a8066c41ffc.jpg)
概念設計のER図であればこんな感じでどうでしょう.

**Comment by yaginuuu** [comment]
概念レベルであればとりあえずこれでおｋだと思います〜。

**Comment by yaginuuu** [comment]
@ryoki1118 
ん？
コミットログはDBで保持するんだっけか？？？

**Comment by ryoki1118** [comment]
構成管理ツールからコミットログを取得してデータベースに保存してから, テーブル数数えてコミット数割り出すのかと思ってた. コミットログをデータベースに保存しない場合, コミット数ってどうやって計算する？

**Comment by ryoki1118** [comment]
US02-F01-SP02が決まり次第, こっちも決められるので, 一時サスペンドします.

**Comment by ryoki1118** [comment]
これでいいですかー
![mitemiru_er](https://cloud.githubusercontent.com/assets/6702920/9440731/3b5bcb88-4aac-11e5-93cb-d85de6d2b3ba.jpg)

**Comment by yaginuuu** [comment]
@ryoki1118 
いいと思いま！す

**Comment by ryoki1118** [comment]
たびたび申し訳ない。
再修正加えました。
![mitemiru_db1-1](https://cloud.githubusercontent.com/assets/6702920/9460345/f3750de0-4b3f-11e5-97af-8c02d08b0cb3.jpg)

**Comment by Altairzym** [comment]
了解です、議論なし

**Comment by ryoki1118** [comment]
更新しました。
これでいいでしょうか？
![mitemiru_db-1-2](https://cloud.githubusercontent.com/assets/6702920/9464845/33633e5a-4b62-11e5-9ebb-7d749f3518d0.jpg)

**Comment by sjc1209** [comment]
一応読みましたが、明日集まる時はちょっとみんなで共有して、説明しながら決めますか。

**Comment by yaginuuu** [comment]
いいと思いますー。

**Comment by ryoki1118** [comment]
@sjc1209 説明ないとわからないってこと？

**Comment by yaginuuu** [comment]
@sjc1209 
issueのやりとりを見れば意味わかると思いますが, それでもわからないというのであっても, **最初からすべてがわからない**というのはとても投げやりで, 自分勝手です.
どこがわからないのか, 理解できないのかをはっきりさせて, **質問する**ようにしてください.

**Comment by yaginuuu** [comment]
少し修正しました〜。
#3

**Comment by sjc1209** [comment]
はい、OKです。

**Comment by ryoki1118** [comment]
#3 と統一しました。
![mitemiru_db-sp01](https://cloud.githubusercontent.com/assets/6702920/9488085/3f26f776-4c12-11e5-810a-0ad1cdf0341f.jpg)

**Comment by yaginuuu** [comment]
@ryoki1118 
またもや修正しているｗ

ちょっとまっててー

**Comment by yaginuuu** [comment]
@ryoki1118 
こいつもclosedしていいと思います！
