### ISSUE TITLE
US01-F01-SP02: システムの動作環境を決定する

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#2]

**Comment by ryoki1118** [comment]
以下参照
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/04%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E5%8B%95%E4%BD%9C%E7%92%B0%E5%A2%83

**Comment by sjc1209** [comment]
おｋです。

**Comment by yaginuuu** [comment]
おｋ。
