### ISSUE TITLE
プロジェクト登録機能が動作しない 大木: 1.0h, 柳沼: 5.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#203]
### DefDone
- [x] heroku再構築

## Overview
Heroku上(master)のアプリケーションにて、正しいRedmine認証情報を入力したにも関わらず、Redmineから情報を取得できない。

**Comment by ryoki1118** [comment]
確認しましたー

**Comment by Altairzym** [comment]
おｋ！
