### ISSUE TITLE
US01-F01-SP01 画面遷移図を変更する 2.5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#206]
## Done definition
2人以上のレビューで承認してもらう。

## What I did.
第三スプリント終了時の画面遷移図(サイトマップ)を作成した。
https://cacoo.com/diagrams/2hkqLdbGl67jp8mb
![3](https://cloud.githubusercontent.com/assets/6702920/10478386/0b144a72-7298-11e5-80b5-77b9b407876e.png)

**Comment by ryoki1118** [comment]
レビューお願いします。

**Comment by yaginuuu** [comment]
@ryoki1118 
個人的にトップ画面はいらないと思った！
>トップ画面の記載内容は各機能の使い方を記載すればいいと思います

最初はいいけど、あとから「もう機能はわかってるよ！」とかってなりそうｗ

**Comment by ryoki1118** [comment]
@yaginuuu 
メトリクス閲覧画面がトップ画面っていうのはしっくりこないんだけど、トップ画面そのものはいらない気もしてきた。作ってみておかしいってなれば、次のスプリントでトップ画面作ればいいか...。

**Comment by yaginuuu** [comment]
@ryoki1118 
んーどうだろう.
>作ってみておかしいってなれば、次のスプリントでトップ画面作ればいいか...。

そうだな、とりあえず、トップ画面ナシの方向でー

**Comment by ryoki1118** [comment]
第二案です。
レビューお願いします。

**Comment by Altairzym** [comment]
いいと思います。

**Comment by yaginuuu** [comment]
@ryoki1118 
おｋ−
以前の画面遷移図は削除しちゃっていいですー
バックアップはあるのでー

**Comment by sjc1209** [comment]
すみません、「プロジェクト管理画面」から「登録済みリポジトリ確認画面」まで、例えば「リポジトリ認証」みたいなボタンを作って、新しいページで認証済みかどうか表示するという感じですか。

**Comment by ryoki1118** [comment]
@sjc1209 そうだね。
「プロジェクト管理画面」でも色分けして、一目でわかるようにはしてほしい。

**Comment by sjc1209** [comment]
わかりました。
