### ISSUE TITLE
US01-F02-SP01 ER図を変更する 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#207]
### DefDone
- [x] システムユーザテーブルを追加する
- [x] 00各種ドキュメント/95図/00ER図を最新版に更新する

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10514746/a7e89bf8-738a-11e5-8f68-b5e1bd1820b3.png)

deviseというライブラリを利用してログイン機能を実装します.
また, adminユーザ管理画面も作成するので, roleテーブルもusersテーブルと多対多の関係で作成します.

### Test
- [x] 入念にチェック

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by ryoki1118** [comment]
> また, adminユーザ管理画面も作成するので, roleテーブルもusersテーブルと多対多の関係で作成します.
一人のユーザが複数のroleをもつこともあるってこと？

**Comment by yaginuuu** [comment]
@ryoki1118 
現状はないっすｗ
でも, 問題も無いと思う！

**Comment by ryoki1118** [comment]
@yaginuuu
必要になる機会があるんかね。
ちなみに外部キーはそれぞれ何になるの？
ER図見た限りだと紐付け方法がわからないかなー

**Comment by yaginuuu** [comment]
@ryoki1118 
おけー
修正します〜

**Comment by yaginuuu** [comment]
@ryoki1118 
修正しました〜

**Comment by ryoki1118** [comment]
@yaginuuu 
見落としがなければおっけです
