### ISSUE TITLE
US01-F02-SP02 テーブルを追加・変更する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#208]
### DefDone
- [x] テーブルを作成

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10495004/7958ef54-72f4-11e5-8599-0993c89dd77b.png)

テーブルを作成しました.

### Test
- [ ] レビューアーからのチェック

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by ryoki1118** [comment]
@yaginuuu ER図の変更はこっちに影響はしない？

**Comment by yaginuuu** [comment]
@ryoki1118 
ER図の方が間違ってた！

**Comment by ryoki1118** [comment]
@yaginuuu 
role_usersってテーブルはあるんだね。
おっけーです

**Comment by Altairzym** [comment]
@yaginuuu ok!
