### ISSUE TITLE
US02-F01-SP01 登録画面を表示する 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#209]
### DefDone
- [x] プロジェクト登録画面が作成されている

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10626992/6dc296fe-77ef-11e5-86d2-605c044aa773.png)

### PullRequestLink
#257

**Comment by sjc1209** [comment]
OKです。

**Comment by ryoki1118** [comment]
プロジェクト終了日の入力欄は作成しないの？

**Comment by Altairzym** [comment]
私の方ちゃんと動いている、おｋ

**Comment by yaginuuu** [comment]
@ryoki1118 
いらねえんじゃないか疑惑ある。

**Comment by yaginuuu** [comment]
@ViBii/owners 
とりあえずclosedします.
