### ISSUE TITLE
US02-F01-SP01: メトリクスを決定する 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#21]
## 第1スプリントで可視化するメトリクス
![image](https://cloud.githubusercontent.com/assets/3440182/9422440/389df31a-48ce-11e5-8d2e-7efea21f5f8a.png)

- 構成管理ツール(Subversion)
    - コミット数
- チケット管理ツール(Redmine)
    - 
![image](https://cloud.githubusercontent.com/assets/3440182/9422441/5d20f160-48ce-11e5-890e-9e3fc39746b6.png)

**Comment by yaginuuu** [comment]
@ViBii/owners 
これでどうでしょう？？

**Comment by ryoki1118** [comment]
いいと思う.
Wikiに記載お願いしますー

**Comment by sjc1209** [comment]
チケット管理ツールから導出したメトリクスはなんですか。よくわかってないですが。

**Comment by sjc1209** [comment]
おｋです。
