### ISSUE TITLE
US02-F01-SP03 プロジェクト情報と開発者情報を確認画面で表示する 4.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#211]
### DefDone
- [x] 確認画面が表示されている
- [x] Redmineの認証チェック
- [x] GitHubの認証チェック

＊認証できていない場合"未認証"と表示されます.
＊また, どちらかは必ず認証しなければならない仕様にしています.

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10680950/750f514c-795f-11e5-989d-8032d7a1fadb.png)

### Usage
```
bin/rake db:migrate
```

### Test
- 意地悪に登録してみてください
- BUG発見しだい対応します.

### PullRequestLink
#257

**Comment by yaginuuu** [comment]
レビューお願いしまっす.
できれば日立ミーティングまでにおねしゃす.

**Comment by sjc1209** [comment]
「また, どちらかは必ず認証しなければならない仕様にしています」これって、
![image](https://cloud.githubusercontent.com/assets/7754274/10683605/8aa428ba-797e-11e5-84d4-4172fb92e806.png)
私は両方登録してない場合、「プロジェクト登録に失敗した」といったが、「プロジェクト一覧」で表示されている。これは正しいですか。

**Comment by yaginuuu** [comment]
これはバグっすね。
どちらも認証できない場合、確認ページに遷移しないで登録ページにリダイレクトされる仕様なんですけど、そうなってないっぽいですね。
フォームにどんな値入れたか教えてもらえる？？

**Comment by sjc1209** [comment]
ただ　必須の「プロジェクト名」と「プロジェクト開始月」入力しただけです。

**Comment by yaginuuu** [comment]
@sjc1209 
承知です.

**Comment by yaginuuu** [comment]
@sjc1209 
こちら修正しました.

**Comment by sjc1209** [comment]
え？また同じ感じですが。

**Comment by sjc1209** [comment]
OKです。
