### ISSUE TITLE
US02-F01-SP04 関連情報をデータベースに保存する 4.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#212]
### DefDone
以下のテーブルが登録されている
- [x] ticket_repositories
- [x] redmine_keys
- [x] redmine_authorities
- [x] version_repositories
- [x] github_keys
- [x] github_authorities
- [x] projects
- [x] developers
- [x] assign_logs

### Overview
DB構成アップデートしました.
以下参照ください.
![image](https://cloud.githubusercontent.com/assets/3440182/10681028/36fa8830-7960-11e5-9d4a-0c798eaad8e2.png)

### Usage
```
bin/rake db:migrate
```

### Test
- 意地悪に登録してみてください
- BUG発見しだい対応します

### PullRequestLink
#257

**Comment by yaginuuu** [comment]
レビューお願いしまっす.
できれば日立ミーティングまでにおねしゃす.

**Comment by sjc1209** [comment]
OKです。
