### ISSUE TITLE
US03-F02-SP01 登録画面のバリデーションを実装する #登録フロー 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#217]
### DefDone
- [x] NULLチェック
    - Redmine, GitHubどちらもにんしょうされていない場合
- [x] 入力形式のチェック
    - Redmine認証チェック
    - GitHub認証チェック
- [x] データベース上とデータとの重複チェック
- [x] パスワードの隠蔽
    - Redmine, GitHub情報フォームの隠蔽
    - redmine_keys, github_keysテーブルに保存する際, 暗号化

### Test
- 登録する際, DefDoneにある内容, それ以外で考えられる内容を考えて登録してみてください

### PullRequestLink
#257

**Comment by yaginuuu** [comment]
レビューお願いしまっす.
できれば日立ミーティングまでにおねしゃす.

**Comment by sjc1209** [comment]
何も書かないまま、「認証」ボタンを押す時、
![image](https://cloud.githubusercontent.com/assets/7754274/10683640/2448767e-797f-11e5-872d-ff6c3ac5bf8d.png)こんな感じになって、これは正しいですか。

**Comment by sjc1209** [comment]
「 データベース上とデータとの重複チェック」これについてチェックする時、完全に同じプロジェクトを登録したが、
![image](https://cloud.githubusercontent.com/assets/7754274/10683745/3bc2e892-7980-11e5-8ead-10fb968c8eca.png)こんなこんな感じになって、これは正しいですか。

**Comment by yaginuuu** [comment]
@sjc1209 
原因わかりました.
修正します.

**Comment by sjc1209** [comment]
「redmine_keys, github_keysテーブルに保存する際, 暗号化」これについてチェックする時、こんな感じになって、![image](https://cloud.githubusercontent.com/assets/7754274/10683847/62abb802-7981-11e5-85c4-8c01eedbbd59.png)これは正しいですか。

**Comment by yaginuuu** [comment]
@sjc1209 
どこのレコード？？
id: 5が正しいです.

**Comment by sjc1209** [comment]
@yaginuuu  
github_keysのテーブルです。

**Comment by yaginuuu** [comment]
@sjc1209 
暗号化されてると思いますー。

**Comment by sjc1209** [comment]
@yaginuuu  おｋ

**Comment by yaginuuu** [comment]
@ViBii/owners 
プロジェクト名と開始月に関しての空白チェックは #268 で実装します.

**Comment by Altairzym** [comment]
私の方問題ないです！

**Comment by ryoki1118** [comment]
残りの件は#268で。
クローズしますー
