### ISSUE TITLE
US02-F01-SP02: メトリクスの導出方法を決定する 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#22]
- 構成管理ツール(Subversion)
    - コミット数
        1. 構成管理ツールファイルからコミット情報取得
        2. 「全てのコミット数」と「特定の開発者のコミット数」をそれぞれ集計
        3. 全コミット数と集計結果(特定の開発者のコミット数)を表示
- チケット管理ツール(Redmine)
    - 
![image](https://cloud.githubusercontent.com/assets/3440182/9422441/5d20f160-48ce-11e5-890e-9e3fc39746b6.png)
        1. 認証して, チケット管理ツールからチケット情報を取得
        2. 特定のチケット担当者のチケットを収集
        3. 収集したチケットのトラッカーごとにチケット数を算出
        4. それらのチケット情報(名前とトラッカー)を％ or 数値で表示する

http://vibi-redmine.herokuapp.com/projects/vibi/wiki/02%E3%83%A1%E3%83%88%E3%83%AA%E3%82%AF%E3%82%B9%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6

**Comment by ryoki1118** [comment]
ごめん, これが終わればデータベースで保持するデータ(ER図の論理モデル)が確定できると思うから, 早めに消化してもらえると助かります.

**Comment by yaginuuu** [comment]
これでいいですかね？？

**Comment by yaginuuu** [comment]
@ViBii/owners 
wikiにも記載しました.
確認よろしく.

**Comment by Altairzym** [comment]
確認しました。ok

**Comment by ryoki1118** [comment]
・コミット数
> 構成管理ツールファイルから全コミットをユーザ名ごとに収集する
1. 構成管理ツールファイルって静的データのこと？
2. データを収集したあと、どうやってコミット数を算出するのか書いて欲しい。コミット数は単純に取得データ数を数えればなんとかなりそうだけど。あと、取得したデータはどこに保持しておくかもちょっと考えて欲しい（ここで決めることじゃない？）。

・役割担当
> 認証して, 担当者ごとにチケット情報(名前とトラッカー)を収集する
同上。どうやって導出するのか全くわからない。

**Comment by sjc1209** [comment]
「収集したデータをどうしたら役割担当が導き出せるのか全くわからない」そうですね。私もそう思います。

**Comment by yaginuuu** [comment]
@ViBii/owners 
導出方法変更しましたー.
レビューお願いします.

**Comment by ryoki1118** [comment]
> b. 特定の開発者のコミットを収集
b. 「全てのコミット数」と「特定の開発者のコミット数」をそれぞれ集計
にしてもらったほうがわかりやすいと思う。

文章としては少しわかりにくいような気もするけど、流れとしてはこれでいいよー。

**Comment by yaginuuu** [comment]
@ViBii/owners 
編集しましたー。
あと1人レビューしたら、closedします！

**Comment by sjc1209** [comment]
おｋです。

**Comment by yaginuuu** [comment]
@sjc1209 さんきゅー
