### ISSUE TITLE
US04-F02-SP01 プロジェクトを選択できる 8.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#224]
このチケットの作業内容はもともと #229 の中の作業内容の一部分です。

### Done
- [x] 四つのグラフをindexページに移動する
- [x] 要らないURLの削除
- [x] 要らないページファイルとコントローラの削除
- [x] 柳沼君のDB変更に合わせる
- [x] 開発者選択リストとプロジェクト選択リストの分離

pullrequest #273

### Review
- ブランチ:zouyimin/graph-in-index
- 現時点master上のtoppageが無くなったので、一応http://localhost:3000/portfolio/productivity_info にアクセス
- 画面で開発者を選択する「Select」を押す
- 次の画面でプロジェクトを選択する 「Select」を押す

**Comment by Altairzym** [comment]
@ViBii/owners  please review

**Comment by yaginuuu** [comment]
@Altairzym 
コレって見積もり0のチケットじゃないすかね？

**Comment by Altairzym** [comment]
@yaginuuu これは最初と5.0の #229  チケット一緒なんだけど。。。大木君が私に「indexに移動と要らないファイルの削除を一つのチケットしないでください」と言ってから、私がこのチケットで作業を実施した。見積もりとか特に言われなかった。。

**Comment by yaginuuu** [comment]
@Altairzym 
どういうこと？？
![image](https://cloud.githubusercontent.com/assets/3440182/10727651/d166dfc0-7c1e-11e5-878c-c1d2e97ca970.png)

日報では消化したことになってるけど, チケットを分割したから実際はまだ消化できてないってこと？？

**Comment by Altairzym** [comment]
@yaginuuu あ、確かに、このチケットの見積もりは0

**Comment by Altairzym** [comment]
@yaginuuu 最初は「要らないファイルの削除と言う作業をこのチケットでやってください」と言われた時、このチケットに関する見積もりの話は全然なかったので、そのまま1pointにした

**Comment by yaginuuu** [comment]
@Altairzym 
おｋ！！確認しました！

**Comment by ryoki1118** [comment]
@Altairzym 
> このチケットの作業内容はもともと #229 の中の作業内容の一部分です。

「#229の作業をこっちに含んでもいいと思う」とは言ったけど、Doneの定義は別だね。一覧表示のページ上部に、プロジェクト選択欄を作成することがDoneの定義です...。

**Comment by Altairzym** [comment]
@ryoki1118 なるほど。。。
