### ISSUE TITLE
F03-SP01 コミット数グラフを非同期処理で読み込む 5.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#225]
pullrequest: #249

**Comment by Altairzym** [comment]
@yaginuuu ちょっと聞きたいですけど、vibi.jsの中の例えばこの部分の中の赤線部分のfunctionの呼び出しは
![image](https://cloud.githubusercontent.com/assets/7775369/10474608/8885ffa2-7273-11e5-828b-64521705c176.png)
どうやって自動的にsaveproject.jsの中の
![image](https://cloud.githubusercontent.com/assets/7775369/10474616/a834e764-7273-11e5-8ce7-d7569ea4324f.png)
このfunctionと対応していますか？「saveproject.js」と言うファイル名はどこでsettingされていますか？

**Comment by yaginuuu** [comment]
関数リテラルで定義されてると思うけど！

**Comment by Altairzym** [comment]
@yaginuuu  @ryoki1118  @sjc1209 　レビューお願いします

**Comment by Altairzym** [comment]
closeします
