### ISSUE TITLE
US02-F01-SP03: メトリクス可視化方法(グラフ化)を決定する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#23]
## Done definition.
2人以上のレビューで承認してもらうこと。

## What I did.
グラフ化方法を提案。

**コミット数: 棒グラフ**
 - 横軸に時間（月単位とか）
 - 縦軸にコミット数

![commit_sample](https://cloud.githubusercontent.com/assets/6702920/9764712/82d415fa-574b-11e5-9c2f-3c9656fde8a9.jpg)

**役割分担: 円グラフ**
 - Redmineから開発者ごとにチケットを収集し、それぞれのチケットのトラッカーを集計して円グラフにする

![role_sample](https://cloud.githubusercontent.com/assets/6702920/9765832/1a25eca8-5751-11e5-9439-07088d22ca96.jpg)

### 第1スプリントでの担当者
一民 0.5h

 **コメント**
このサイトでhttp://qiita.com/awakia/items/d064c772b759333c209a
沢山のライブラリが参照できるらしい
今スプリントで表示したいのはコミット数と役割分担の話なので、
コミット数項目を棒グラフで表示しよう！
D3.jsを利用して、表現する

**Comment by Altairzym** [comment]
このサイトでhttp://qiita.com/awakia/items/d064c772b759333c209a沢山のライブラリが参照できるらしい

**Comment by Altairzym** [comment]
棒グラフにしよう！

**Comment by ryoki1118** [comment]
何を棒グラフにするの？

**Comment by Altairzym** [comment]
コミット数項目を棒グラフにする、役割担当はまだ分からない。。。

**Comment by ryoki1118** [comment]
コミット数は棒グラフでいいと思う。
役割担当はUS02-F01-SP02がCloseしたら決めよう。

**Comment by ryoki1118** [comment]
役割分担はどうなった？

**Comment by yaginuuu** [comment]
いいと思います。

**Comment by Altairzym** [comment]
いいと思います。

**Comment by Altairzym** [comment]
因みに役割分担はredmineの中、各チケットのlabelですね

**Comment by ryoki1118** [comment]
Labelってかトラッカーだね
クローズします
