### ISSUE TITLE
US06-F04-SP02 工数グラフを修正する 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#237]
- [x] 工数グラフの修正（0hを表示しないようにする）

pullrequest #275 

### Review
- Branch: zouyimin/change-cost-graph
- http://localhost:3000/portfolio/index の中の三番目「開発者、プロジェクト選択画面 」をクリックする
- 開発者とプロジェクト選択してから、工数グラフが以下のように表示する
![image](https://cloud.githubusercontent.com/assets/7775369/10725894/be7c27aa-7c12-11e5-85ce-1d3ef5ce0253.png)

**Comment by Altairzym** [comment]
@ViBii/owners  please review

**Comment by yaginuuu** [comment]
@Altairzym 
@ryoki1118 
このチケットってDoneの定義これでおｋすか？

**Comment by Altairzym** [comment]
@yaginuuu 一応日立の方はまず全部0hのコラムを非表示になってくださいと言われたので、とりあえず削除した

**Comment by yaginuuu** [comment]
@Altairzym 
それならおｋです！
確認しました！

**Comment by Altairzym** [comment]
@yaginuuu ありがとう！

**Comment by ryoki1118** [comment]
@Altairzym @yaginuuu 
Doneの定義は#236 の実装だね。
ってもこのグラフは廃止になったので、まぁこれでいいかな。笑

**Comment by Altairzym** [comment]
@ryoki1118 これmasterにマージ？それとも廃止？

**Comment by yaginuuu** [comment]
@Altairzym 
mergeでいいと思います!!

**Comment by Altairzym** [comment]
@yaginuuu ok!
