### ISSUE TITLE
US07-F01-SP01 システムユーザの登録画面を作成する 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#238]
### DefDone
- [x] システムユーザの登録画面が作成されている

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10496396/91e183a4-72fb-11e5-9297-9a2485b2f459.png)

レイアウトキモいけど, とりあえず実装はおわってます.

### PullRequestLink
#251

**Comment by ryoki1118** [comment]
@yaginuuu
登録できました。
バリデーションも問題ないかと。

**Comment by Altairzym** [comment]
自分の方問題ないです！
