### ISSUE TITLE
US02-F01-SP04: グラフ化ツールを決定, 導入する 5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#24]
## 導入の方法と公式サイト
- D3.jsの公式サイト:http://d3js.org/
- install方法についてはD3のドキュメントの方：https://github.com/mbostock/d3/wiki
が書いてありますが、二つのやり方がる
   - サイト：https://github.com/mbostock/d3/releases
からzipファイルをダウンロードする
   - ダウンロードしたくない場合、htmlに
     ```
     <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
     ```
を追加するだけで、D3.jsを引用することができる

#109 を見てください。

**Comment by Altairzym** [comment]
このIssueの概要部分もう書いたけど、今回のプロジェクトに対して、どのような導入方式がいいですか？

**Comment by yaginuuu** [comment]
@Altairzym 
D3.jsを導入するのであれば、2番めのイントール方法がいいと思います！
メリットデメリットを皆に説明しよう！

**Comment by Altairzym** [comment]
@yaginuuu 
概要を更新した、そちを見てください。

**Comment by yaginuuu** [comment]
@Altairzym 
あーちがうちがう！ｗ
>グラフ化ツールを決定, 導入する

だから、いろんなグラフ化ツールのメリットデメリットのことだよー。
インストール方法は2番目のコードを書く方法がいいです！

**Comment by yaginuuu** [comment]
closedしていいと思います！
