### ISSUE TITLE
US07-F01-SP03 関連情報をDBに保存する 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#240]
### DefDone
- [x] 新しいユーザを登録できる
- [x] 登録後ログイン状態になる

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10514235/9526bb06-7387-11e5-918c-553adaaddec8.png)

### Test
以下の点を観て欲しいです.

- [x] ユーザ登録画面のバリデーションは有効になっているか？
    - [x] 存在チェック
    - [x] nullチェック
    - [x] パスワードは8文字以下, 半角英数字
    - [x] 確認パスワードが違うとダメ
- [x] 登録ボタンを押すとログイン状態になっているか？
- [x] usersテーブルに登録されているか？

### PullRequestLink
#251

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by ryoki1118** [comment]
@yaginuuu 
> パスワードは8文字以下, 半角英数字
8文字以上の間違い？
8文字未満は弾かれるね。

**Comment by yaginuuu** [comment]
@ryoki1118 
そうそうそうです.

**Comment by ryoki1118** [comment]
@yaginuuu 
全部おっけーです

**Comment by Altairzym** [comment]
@yaginuuu 問題ないです。
