### ISSUE TITLE
US07-F02-SP01 ログインする 4.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#242]
### DefDone
- [x] ログイン画面の作成
- [x] ログイン処理の実装
- [x] ログイン中のヘッダ表示の作成 

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10514001/3c61d984-7386-11e5-9a78-8fd1d3a97e61.png)

![image](https://cloud.githubusercontent.com/assets/3440182/10514020/527adee6-7386-11e5-848c-5de1574c8c8b.png)

### Test
以下の点を観て欲しいです.
- [x] 未ログインの場合は他のページに遷移できず, ログイン画面にリダイレクトされる仕様になっているか？
- [x] ログインフォームはnullチェック出来ているか？
- [x] DBに存在しないユーザの場合はログインできない仕様になっているか？
- [x] 下部リンク(初めての方はこちらへ)は正しく遷移するか？
- [x] エラー文等日本語に対応されているか？
- [x] ログイン後, ヘッダーにログインIDとログアウトリンクが表示されているか？

その他アラ探しして欲しいです〜.

### PullRequestLink
#251

**Comment by yaginuuu** [comment]
レビューお願いしまっす.

**Comment by ryoki1118** [comment]
@yaginuuu
「Test」に書かれている欄は確認しました。

**Comment by Altairzym** [comment]
@yaginuuu おｋ、いいと思います！
