### ISSUE TITLE
US07-F02-SP02 ログアウトする 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#243]
### DefDone
- [x] ログインページへの遷移
- [x] ログアウトボタンの作成

### Overview
![Alt Text](https://i.gyazo.com/4a24a0585f3af8b5870ae3996c737c84.gif)

### Test
以下の点を観て欲しいです.
- [x] ログイン状態でログアウトボタンを押すと, ログアウト状態になる

### PullRequestLink
#251

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by ryoki1118** [comment]
@yaginuuu 
適当なIDとPW入れたときのアラート文章おかしい？
メールアドレスじゃなくてユーザIDじゃない？
<img width="1175" alt="screenshot 2015-10-15 22 25 49" src="https://cloud.githubusercontent.com/assets/6702920/10514926/d67e8a6c-738b-11e5-9ac4-7c9cc2854c87.png">

**Comment by yaginuuu** [comment]
@ryoki1118 
そうだねｗ！！
ありがっと！
なおします〜

**Comment by ryoki1118** [comment]
@yaginuuu 
あと個人的な好みかもしれないんだけど、ログインメニューにアラート文が常にいるの気持ち悪いかも。笑
それとログアウトのリンクはボタンの方が分かりやすいかなぁ
<img width="1167" alt="screenshot 2015-10-15 22 27 12" src="https://cloud.githubusercontent.com/assets/6702920/10514954/00a66954-738c-11e5-98e5-2bab2d4ad9bc.png">

**Comment by yaginuuu** [comment]
@ryoki1118 
pushしますた！

>あと個人的な好みかもしれないんだけど、ログインメニューにアラート文が常にいるの気持ち悪いかも。笑

笑. とりあえず, issue化お願いしまっす！！

>それとログアウトのリンクはボタンの方が分かりやすいかなぁ

ログイン後のヘッダーってこと？
んーちょっと考える〜
とりあえずissue化で！

**Comment by ryoki1118** [comment]
> ログイン状態でログアウトボタンを押すと, ログアウト状態になる

確認しました。

**Comment by Altairzym** [comment]
@yaginuuu いいと思います
