### ISSUE TITLE
US07-F03-SP01 開発者管理の際, システムユーザが登録した情報のみを表示  #各種管理 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#244]
### DefDone
- 各種管理画面(開発者)でシステムユーザが認証したRedmineデータ, Githubデータに紐付いているプロジェクトに所属している開発者のみ表示されている

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10776796/11fba072-7d58-11e5-9d23-4f3ba7ccafbf.png)

### Test
Doneの定義通りです.
システムユーザを複数作成し, 確認よろしくお願いしまっす.

### PullRequestLink
#276

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by Altairzym** [comment]
ok!!!!
