### ISSUE TITLE
US07-F03-SP02 プロジェクト情報の際, システムユーザが登録した情報のみを表示 #各種管理 1.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#245]
### DefDone
- 各種管理画面(開発者)でシステムユーザが認証したRedmineデータ, Githubデータに紐付いているプロジェクトのみ表示されている

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10776820/604b86e8-7d58-11e5-9580-3da2b5c355fd.png)

### Test
Doneの定義通りです.
システムユーザを複数作成し, 確認よろしくお願いしまっす.
 
### PullRequestLink
#276

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっす.

**Comment by Altairzym** [comment]
@yaginuuu 私の方ちょっと問題があります。。。
先ず新規ユーザ、そして各種管理に行くと、なんの情報もなかった
プロジェクトを登録すると、他の人が登録した情報も一緒に表示した

**Comment by yaginuuu** [comment]
@Altairzym 
なんの情報もなかったプロジェクトってなに？？
それは登録できない仕様になっているから考慮しなくてもいいと思う！

**Comment by Altairzym** [comment]
ok!!!!

**Comment by yaginuuu** [comment]
@Altairzym 
レビューさんきゅ！！！！

**Comment by ryoki1118** [comment]
@yaginuuu こっちは多分問題ない
