### ISSUE TITLE
US07-F03-SP05 システムユーザ情報の際, システムユーザが登録した情報のみを表示 #各種管理 2.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#248]
### DefDone
- [x] 管理画面を導入
- [x] rootのみの利用可能な機能

### Overview
![image](https://cloud.githubusercontent.com/assets/3440182/10536273/c8ad78be-7424-11e5-838c-51d5964802f2.png)

スーパユーザのみ認証できる管理画面を作成しました.
そこで, システムユーザをRUDできます.

### PullRequestLink

**Comment by Altairzym** [comment]
いいと思います！

**Comment by sjc1209** [comment]
OKです。
