### ISSUE TITLE
US02-F01-SP02: 分析ツールを決定, 導入する 5.0ｈ+9.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#25]
#167    に参照してください。

StatSampleを利用して、正規分布のサンプルプロフラムを書きました。
![image](https://cloud.githubusercontent.com/assets/7754274/9927747/09b26656-5d5c-11e5-997b-4df004be32a6.png)
結果はこんな感じになりましたが、改行はできなくて、ちょっと見づらいです。
実際に端末で運行した結果はこんな感じです。
![image](https://cloud.githubusercontent.com/assets/7754274/9927789/594942de-5d5c-11e5-9826-c19efea70fd5.png)

## How to check
ブラウザで、http://localhost:3000/datasamples/indexにアクセスし、結果が出るはずです。
## 担当者
孫

**Comment by ryoki1118** [comment]
・StatSampleの学習コストが重い理由
・MikonとIRubyはどんなもの？

あと、ここで可視化の話は必要ないです。
統計処理ができるライブラリであれば問題ないかと思いますー

**Comment by sjc1209** [comment]
学習コストじゃなく、その上のWEBページから見ると実際にデータを解析する時、手間がかかりそうです。「Rubyでデータ解析をする際にはStatsampleが有名ですが、実際のデータの取扱いや可視化が非常に面倒なのがネックでした」って書いてあります。
![qq 20150828221714](https://cloud.githubusercontent.com/assets/7754274/9547093/d308e258-4dd2-11e5-97f1-10d0d369a3ce.png)

**Comment by sjc1209** [comment]
ここに書いてあるように、MikonはRUBYでデータの読み込みや操作とか扱えって、多分MikonとStatample両方導入する必要があると思う。

**Comment by ryoki1118** [comment]
じゃMikonとStatsampleが入ればいいて感じかな？
IRubyはWeb版統合開発環境（JavaでいうEclipse）なら、関係ない話かね。

**Comment by sjc1209** [comment]
はい、これからmikonとStatampleを導入します。

**Comment by sjc1209** [comment]
Statampleをmitemiruに導入した。ご確認ください。mikonはとりあえず、第一スプリントで導入しないことにする、どうですか。

**Comment by ryoki1118** [comment]
> Statampleをmitemiruに導入した。ご確認ください。
どのブランチ？

>mikonはとりあえず、第一スプリントで導入しないことにする、どうですか。
Statsampleで問題ないならいいよ

**Comment by sjc1209** [comment]
masterです。

**Comment by ryoki1118** [comment]
masterはレビューが終わって他の人の許可をもらってからマージすること。
branchを作って、そこで編集してからpull requestを出してくださいー

**Comment by ryoki1118** [comment]
>masterです。

どちらにせよ、masterにコミットした履歴はないね。

**Comment by sjc1209** [comment]
今回はMITEMIRUのフォルダの下にサンプルファイルを入れて、ファイルを実行しました。これでSTATSAMPLEのライブラリの導入が成功したと言えますか。レビューお願いします。
@ViBii/owners

**Comment by yaginuuu** [comment]
@sjc1209 
えーと、MVCの中で書いて欲しいです。
これはただ、ディレクトリの中にファイルをいれているだけです。
Controller, Model, Viewの中！！！

**Comment by yaginuuu** [comment]
あとプルリクの方にもissueの番号記述してほしい。
もどるのめんどくさいｗ

**Comment by sjc1209** [comment]
はい、わかりました。

**Comment by yaginuuu** [comment]
@sjc1209 
いいね！
あと、これからはテスト落ちてない状態まで実装してから、レビューしてもらってください。

**Comment by sjc1209** [comment]
えっと、MVCの中で書くというのは、そのサンプルファイルを、例えばcontrollerの中で入れますか。

**Comment by yaginuuu** [comment]
@sjc1209 
ちょっとそこは勉強して下さい。
http://dotinstall.com/lessons
これとかやってください。

**Comment by sjc1209** [comment]
Ruby　On　Railsの勉強ですか。

**Comment by ryoki1118** [comment]
Ruby on RailsでのMVCモデルの扱い方を頭に入れて欲しいって感じかな。バックグラウンド処理はControllerに書いて、表示処理はViewに記述するってのが基本かな。

**Comment by yaginuuu** [comment]
@sjc1209 
うん。

**Comment by sjc1209** [comment]
はい、それはわかります。多分問題なのはサンプルファイルのソースコードがよくわからないですね。

**Comment by ryoki1118** [comment]
ここに統計量の導出方法とか書いてあるから、読みながらソースコード書いてみな。
http://medfreak.info/?p=653

**Comment by sjc1209** [comment]
はい、わかりました。ありがとうございます。

**Comment by sjc1209** [comment]
今新しいブランチを作って、何も修正しない状態で rails s すると、問題がありました。
この前もうmasterでgit pullして、rails s で問題なかったです。
![qq 20150914165454](https://cloud.githubusercontent.com/assets/7754274/9844857/a1da8a06-5b01-11e5-9504-21ebdae87184.png)

**Comment by sjc1209** [comment]
新しいブランチを作る時、何も修正してないのに、GEMFILEに「gem 'statsample'」というコードが自動的に追加された。そして、サーバを起動して、問題が発生した。
そして、私はGEMFILEに　mysqlのところ　「gem 'mysql2', '~> 0.3.18'」　このように変えました。問題は無くした。これで大丈夫ですか。 @ryoki1118  @yaginuuu

**Comment by ryoki1118** [comment]
> 新しいブランチを作る時、何も修正してないのに、GEMFILEに「gem 'statsample'」というコードが自動的に追加された。そして、サーバを起動して、問題が発生した。
過去に自分で追加したんじゃないの？
コミット履歴に書いてあるけど。

> そして、私はGEMFILEに　mysqlのところ　「gem 'mysql2', '~> 0.3.18'」　このように変えました。問題は無くした。これで大丈夫ですか。
バージョンはなんで0.3.18以降にしたの？

**Comment by yaginuuu** [comment]
ん？
これに関してのissueがclosedされてないのに導入されてるの？笑

それは非常におかしい笑

**Comment by sjc1209** [comment]
今多分GITのコミット機能が壊れたみたいで、PUSHしてもORIGINで反応がない。

**Comment by yaginuuu** [comment]
DBのバージョンは決めたはずだから、どうしよう。

**Comment by sjc1209** [comment]
@yaginuuu その前のブランチが問題が発生して、新しいブランチでもう一度やり直したいと思った。

**Comment by sjc1209** [comment]
いや、今多分自分のパソコンの問題です。修正してもまた元に戻す。原因がわからないけど。

**Comment by yaginuuu** [comment]
んーちょっとこっちでも見てみるー

**Comment by sjc1209** [comment]
えっと、多分そっちはまた修正してないバーションです。こちは修正して直したが、PUSHができなくて、ORIGIN側は変わってないと思う。その上、ローカルでまた元に戻した。。。

**Comment by ryoki1118** [comment]
@sjc1209 
> 今多分GITのコミット機能が壊れたみたいで、PUSHしてもORIGINで反応がない。

gitが壊れる可能性はほとんどないので操作ミスです。
あとstatlibraryってブランチ消してstatってブランチを作ったみたいだけど、更新履歴とか全部引き継いでるね。ちょいよくわからんけど。

@yaginuuu 
> DBのバージョンは決めたはずだから、どうしよう。

mysql2の話は特にしてないから適当に決めてもいいと思う

**Comment by sjc1209** [comment]
そうですね。新しいブランチを作ったのに、どうして履歴が引き継いでるかわからないですが。。

**Comment by yaginuuu** [comment]
1度masterに戻ってからブランチ作らないと引き継がれるよー。前のブランチから子ブランチ化してるんだと思います！

**Comment by yaginuuu** [comment]
なので、今どのブランチで作業しているかは意識したほうがいいよ！

**Comment by yaginuuu** [comment]
masterにcheckoutして、最新にしたらDBの話も問題ないと思いますー。

**Comment by sjc1209** [comment]
レビューお願いします.
@yaginuuu  @ryoki1118  @Altairzym

**Comment by Altairzym** [comment]
私の方問題ないです！

**Comment by yaginuuu** [comment]
ご苦労さまです。
closedしていいです。
