### ISSUE TITLE
システムユーザ管理画面の変更&herokuにDBを適応 3.5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#256]
### DefDone
- [x] heroku上のサービスが正常に動く

### Test
https://mitemiru.herokuapp.com/
以上から確認していただきたいです.

### PullRequestLink
#255 
#251

**Comment by ryoki1118** [comment]
![screenshot 2015-10-19 10 06 33](https://cloud.githubusercontent.com/assets/6702920/10567835/3a163f88-7649-11e5-9388-e041e2909a1f.png)
ここの戻るボタン押すとエラー吐くよー
MVCのリンク整備漏れかな？

**Comment by yaginuuu** [comment]
@ryoki1118 
あー見落としてた.
ちょっとだし強制マージします.

**Comment by Altairzym** [comment]
すごいです。。。いいと思います。
