### ISSUE TITLE
グラフの一覧表示画面イメージを作成する 1.5h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#258]
## Overview
グラフの一覧表示画面のUIによって各グラフの動作仕様が異なるため、各グラフの見せ方を決める前に一覧表示画面のイメージを共有したい。

## Done definition
**3人以上のレビューで承認してもらう。**

## What I did.
 - [x] 一覧画面レイアウトの作成

開発者未選択
![scn_0001](https://cloud.githubusercontent.com/assets/6702920/10576450/5c5e0698-769e-11e5-9cef-9acbf1758456.jpg)

開発者を選択
![scn_0002](https://cloud.githubusercontent.com/assets/6702920/10576460/722d8a70-769e-11e5-87b5-b75fae13292d.jpg)

 - [x] グラフ遷移の流れを設計
1. プロジェクト名を選択
2. グラフが一覧表示される
3. 開発者を選択すると、すべてのグラフ上でその開発者がハイライトされる

## Note
案があればコメントください。大歓迎です。

**Comment by ryoki1118** [comment]
レビューお願いしますー。グラフ一つひとつの見せ方は置いておいて、画面全体のレイアウトやらフローについてコメントをください。

**Comment by yaginuuu** [comment]
@ryoki1118 
円のグラフなんだけど, プロジェクトメンバー多い時のこと考えたらただ円を人数分並べるっていうのはちょっと違和感ある....

>プロジェクト名を選択
>グラフが一覧表示される
>開発者を選択すると、すべてのグラフ上でその開発者がハイライトされる

フローに関しては異議なしっす.

**Comment by ryoki1118** [comment]
@yaginuuu 
三末先生も言ってたけど、情報量は少なくても一目で全体を見る手法としては一般的だし、数十人規模でも見る分にも俺はいいかなぁって思ってる。
参考: http://bl.ocks.org/chaitanyagurrapu/6007521

**Comment by ryoki1118** [comment]
@yaginuuu 開発者選択時にはそれが大きく表示されるようにしてもいいかもね。

**Comment by Altairzym** [comment]
イメージはいい感じです。

**Comment by ryoki1118** [comment]
@sjc1209 3人全員にレビューもらいたいので待ってますー

**Comment by yaginuuu** [comment]
@ryoki1118 
うん. つくってみてからまた議論しませう.

**Comment by sjc1209** [comment]
開発者選択ボタンとかどこにありますか。例えば、開発者選択した後、「プロジェクト名」の右に「開発者名」を表示すれば、わかりやすいね。

**Comment by ryoki1118** [comment]
@sjc1209
 あーそうだね。
どこかに選択済みの開発者は表示するようにしよう。
