### ISSUE TITLE
US04-F01-SP01: コミット情報を取得し,コミット数を集計する 3.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#26]
### ToDo
- [x] GitHub API を使って、コミット情報を取得する方法の研究
- [x] 実装する

#168 を見てください
### 方法
```
https://api.github.com/repos/ViBii/mitemiru/branches
```
にアクセスすれば、branchが表示できる
```
https://api.github.com/repos/ViBii/mitemiru/commits?author=zouyimin88@gmail.com
```
にアクセスすれば、master上のcommitが表示できる
```
https://api.github.com/repos/ViBii/mitemiru/stats/contributors
```
にアクセスすれば、master上のcommitの統計も表示できるけど、他のやり方と比べると、結果が違う。。
### 結論
```
https://api.github.com/repos/ViBii/mitemiru/contributors
```
を利用したほうがいい
## 前担当者
柳沼

**Comment by Altairzym** [comment]
今までGItHub APIを研究したけど、GItHub APIはmasterに対するコミット、あるいはあるbranchの中のコミット数が取れるけど、branchの中のコミットを取る場合、そのbranch名を知らないといけないです、もう削除したbranchに対するコミットはどうすればいいでしょう？

**Comment by ryoki1118** [comment]
消去済みは放置していいとして、Closeされたブランチ名って取得できないの？

**Comment by yaginuuu** [comment]
@Altairzym 
これって、US03じゃなくない？？

**Comment by Altairzym** [comment]
@yaginuuu そうだね、間違いました。。。

**Comment by sjc1209** [comment]
OKです。closeしていいです。

**Comment by Altairzym** [comment]
そうだね、closeします
