### ISSUE TITLE
US05-F01-SP01 メトリクスを決定する 5.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#261]
## Overview
可視化するメトリクスの検討と、新たなグラフ案を提案する。
できれば複数。

## Done definition
**3人以上のレビューで承認してもらう。**

## What I did.
 - [x] API仕様の整理

GitHub API: https://developer.github.com/v3/
 - [x] メトリクスの検討

#### 可視化メトリクス:【専門性】
選択理由: 開発者の使用言語とコーディング実績は有用な情報になると感じたため。

開発者ごとにコミット情報を収集。
編集ファイルの種別(拡張子)を集計し、専門性を導き出す。

例:
***.javaファイルの編集(コミット)が多い
-> その開発者はJavaを扱える

#### グラフの概要
 - 対象メトリクス: 専門性
 - 利用データ: コミットログ, GitData(Blobs, Commits, Trees)

#### データ取得の方針
mitemiruを例として記載する。

1. コミット履歴を全て取得する
https://api.github.com/repos/ViBii/mitemiru/commits

2. それぞれのコミット情報から、編集ファイル名を収集する
https://api.github.com/repos/ViBii/mitemiru/commits/aae4413aa10520167a741d38c5ef3c0d15557ae5
※ 他人がMergeした場合、ソースコードを書いていないにも関わらずその人のコミット実績になってしまうため、Mergeは省く(親コミットを2つ持つコミットはMerge)。

3. 集計した編集ファイル数を拡張子ごとに集計し、グラフ化する
**※ 三末先生と相談しましょう。**

## Comment
 - ファイルの中身は見えないがソースコードの構造は取得できるため、Treemapと組み合わせた可視化を実現したい。
参考: http://bl.ocks.org/mbostock/4063582

**Comment by ryoki1118** [comment]
一つ案を出したので、コメントください。

**Comment by Altairzym** [comment]
@ryoki1118 あ、なるほど！いいと思います！！確かに、filesと言う属性があって、その中から拡張子が取得できる

**Comment by yaginuuu** [comment]
>集計した編集ファイル数を拡張子ごとに集計し、グラフ化する

拡張子っていうよりもファイル名でくくったほうがいい時もあるかも.
(例えばこの人はcontroller多く書いてるとかこの人はview側多く書いてるとか)
例えば, railsプロジェクトだったらほとんどの拡張子がrbになってしまうし..

んーでも評価者の立場から見たら, どんな言語を書いたっていう情報も必要ですねえ.
どっちも必要かもー.

**Comment by ryoki1118** [comment]
@yaginuuu 
> 拡張子っていうよりもファイル名でくくったほうがいい時もあるかも.
> (例えばこの人はcontroller多く書いてるとかこの人はview側多く書いてるとか)
> 例えば, railsプロジェクトだったらほとんどの拡張子がrbになってしまうし..

> んーでも評価者の立場から見たら, どんな言語を書いたっていう情報も必要ですねえ.
> どっちも必要かもー.

どっちもあるといいなとは思ってるー
どちらにせよ方針はこれでよい？
あとは三末先生と話ながら細かい仕様決めようかと思ってる。

**Comment by yaginuuu** [comment]
ok

**Comment by ryoki1118** [comment]
@sjc1209 孫くんのレビュー待ちです

**Comment by sjc1209** [comment]
いいと思います。
