### ISSUE TITLE
円グラフ仕様の変更 0.5h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#265]
## Overview
#234で考案したグラフ仕様を変更する

## Done definition
2人以上のレビューで承認してもらう。

## What I did.
 - [x] 変更グラフ案の作成

#### イメージ画像
 - BUGのトラッカーは予定通りに終えたケース
 - Designのトラッカーは予定以上に時間がかかったケース
 - Testのトラッカーは予定よりも早く終わったケース

前回の案
<img width="400" alt="screenshot 2015-10-19 22 01 53" src="https://cloud.githubusercontent.com/assets/6702920/10578462/3cd9e5a8-76ad-11e5-8012-4c23420cef5c.png">
<img width="427" alt="screenshot 2015-10-19 22 02 07" src="https://cloud.githubusercontent.com/assets/6702920/10662970/e54feb28-78f2-11e5-8832-d1adccf7b907.png">

今回の案
<img width="435" alt="2015-10-22 19 26 23" src="https://cloud.githubusercontent.com/assets/6702920/10662961/dd82d608-78f2-11e5-8c25-6291ff3dc7b7.png">
<img width="426" alt="2015-10-22 19 26 35" src="https://cloud.githubusercontent.com/assets/6702920/10662977/ed359248-78f2-11e5-9582-4d521f340ace.png">

##### 変更点
前回は実績工数が大きくなるほど円が大きくなる仕様だったが、今回は生産性に比例して円が大きくなるようにした。

**Comment by ryoki1118** [comment]
仕様変更したいので、コメントをお願いします（実装中なので早急に）。

**Comment by yaginuuu** [comment]
おｋ

**Comment by ryoki1118** [comment]
あ、生産性の算出方法だけど、(見積もり/実績)です。

**Comment by sjc1209** [comment]
なるほど、いいと思います。

**Comment by Altairzym** [comment]
オッケー
