### ISSUE TITLE
プロジェクト開始月に関していろいろ #登録フロー 6.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#268]
### DefDone
- [x] デフォルトは今日にする
- [x] 保存するデータを日付型に変更
- [x] NULLチェック
    - プロジェクト名, プロジェクト開始日がNULLの場合
- [x] Redmineのホスト名のhttps://チェック処理
- [x] 登録フローの文言チェック
- [x] カラムの修正(urlをなくす)
- [x] 孫君指摘のBUG修正
    - [x] DB上にGitHub認証データがあると登録失敗する

### Overview
- デフォルトのプロジェクト開始月は今日に設定
- プロジェクト開始月はDate型で保存
- プロジェクト名, プロジェクト開始日のNULLチェック
- Redmineのホスト名に"http://", "https://"が含まれる場合も保存可能
- version_repositoriesテーブルを編集
    - urlカラムを削除
    - project_name, repository_name追加
- ticket_repositoriesテーブルを編集
    - urlカラムを削除
    - host_name, project_name追加

### Usage
```
bin/rake db:migrate
```

### Test
- 上記の変更に関して, 意見があればよろしくお願いしまっす.

### PullRequestLink
#274

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いしまっすー

**Comment by sjc1209** [comment]
![image](https://cloud.githubusercontent.com/assets/7754274/10722111/05926cda-7bf0-11e5-80fd-d9bc11aba0f8.png)
私はこんな感じで登録しましたが、プロジェクト登録失敗と表示されて、同じGithub上プロジェクトは重複登録できないってことですか。

**Comment by sjc1209** [comment]
![image](https://cloud.githubusercontent.com/assets/7754274/10722118/19896658-7bf0-11e5-97ce-ee59ba3bfabd.png)

**Comment by yaginuuu** [comment]
@sjc1209 
再現できない......

**Comment by yaginuuu** [comment]
@Altairzym 
ちょっとレビューしてくれますか？？

**Comment by sjc1209** [comment]
@yaginuuu えっと、私はまた同じ問題がある。git pullで柳沼君のブランチを最新にしたけど。

**Comment by sjc1209** [comment]
しかも、同じRedmineのプロジェクトを登録したら、また「プロジェクト登録に失敗」と表示する。他の人はどうかな。 @ryoki1118  @Altairzym

**Comment by yaginuuu** [comment]
@sjc1209 
slackの方で言及してます！
mysqlの方で文字コードの設定をしていないのが原因です～.
今, 一民が修正してるからあとから共有しますう.

**Comment by yaginuuu** [comment]
@ryoki1118 
ちょっと @sjc1209 と @Altairzym のローカル環境におけるmysql設定に問題があると思うので, ミスターオオキレビューしてもらえませんか？？

**Comment by ryoki1118** [comment]
@sjc1209 @yaginuuu 
登録済みのRedmineリポジトリでも普通に登録はできたよ。
関係あるか知らんけど、画像部分の23行目がおかしい。
<img width="695" alt="2015-10-26 23 04 26" src="https://cloud.githubusercontent.com/assets/6702920/10730902/2991ec00-7c36-11e5-9cf8-c6a744937a77.png">

**Comment by yaginuuu** [comment]
@ryoki1118 
あーそこは特に関係ないー。

**Comment by Altairzym** [comment]
![image](https://cloud.githubusercontent.com/assets/7775369/10748119/27bd5fb2-7ca0-11e5-8b61-9774a65cc3c1.png)
成功です

**Comment by yaginuuu** [comment]
@Altairzym 
その状態で
・Redmine片方だけ認証
・Github片方だけ認証
・それらにもう片方の認証を付け加える
とかやってみてもらえますか？？
そしてDBの中身もみてもらいたい

**Comment by ryoki1118** [comment]
@yaginuuu 
同じプロジェクトを何度か繰り返して登録して欲しいってことでいいの？
とりあえずそれでやってみたけど、特に問題なく上書きされたよ。

**Comment by yaginuuu** [comment]
@ryoki1118 
おｋおｋ:shipit:
ありがっと！

@Altairzym 
これclosedしますねーーー
