### ISSUE TITLE
US04-F01-SP02: 集計したコミット数をグラフ化し, 表示する 25.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#27]
## Done definition.
#172 をレビュー、マージしてもらう

## What I did.
#172 参照

## P.S.
D3.jsと必要ないのにAjaxの勉強をしていたのでものすごく時間がかかった。
ただ、今後のチケットの消化時間を大幅に削減できると思う。

**Comment by ryoki1118** [comment]
#16の画面遷移図に従うとすれば、ポートフォリオ機能の画面1で開発者とプロジェクトが指定された状態でコミット数の閲覧をするんだよね？だったらコミット数の閲覧ページで開発者もプロジェクトも選択するフォームはいらないってことでよいの？

**Comment by yaginuuu** [comment]
@ryoki1118 
>#16 の画面遷移図に従うとすれば、ポートフォリオ機能の画面1で開発者とプロジェクトが指定された状態でコミット数の閲覧をするんだよね？
そうです！
>だったらコミット数の閲覧ページで開発者とプロジェクトを選択するフォームはいらないってことでよいの？
そうです！
なので、今のところはidが1番最初の開発者とかに指定して表示できていればいいと思います！他のUSとは独立されているはずなので！

**Comment by ryoki1118** [comment]
マージしたのでクローズしていいすかね

**Comment by yaginuuu** [comment]
良いっす
