### ISSUE TITLE
チケットのトラッカーを可視化するグラフのBUG

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#289]
### BUG問題
- すべてのユーザを取得して表示している
- プロジェクトに所属する, 開発者のみを表示しなければならない.

pullrequest #297 

### 参考したURL
http://vibi-redmine.herokuapp.com/projects/vibi/memberships.xml

**Comment by sjc1209** [comment]
「メトリクスを見る」で、プロジェクトを選択し、表示したグラフは以下のようになる。プロジェクトに所属しない人のグラフが出った。
![_20151116153526](https://cloud.githubusercontent.com/assets/7754274/11175668/016c9624-8c78-11e5-8594-dd70c5187fd5.png)

**Comment by Altairzym** [comment]
@yaginuuu  @ryoki1118 
コードからみると、
![image](https://cloud.githubusercontent.com/assets/7775369/11205832/beea6686-8d45-11e5-91d8-fe244bf55359.png)
redmine API経由で開発者データを取得している
このチケットの作業内容は**実績工数が0の開発者を表示しないように**変更しますか？
