### ISSUE TITLE
プロジェクト削除における関連テーブル削除を実装する 4.0h

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#291]
### DefDone
- [x] プロジェクトを削除すると関連テーブルが削除されている

### Overview
以下の項目を実装した.
- developerを削除すると, 関連するassign_logが削除される
- projectを削除すると, 関連するassign_logが削除される
- ticket_repositoryを削除すると, 関連するredmine_keyが削除される
- version_repositoryを削除すると, 関連するgithub_keyが削除される

### Test
- [ ] 管理者でログインして試してみてください

### PullRequestLink
#332

**Comment by sjc1209** [comment]
消化時間とチェックボックスをちゃんとやってください。

**Comment by sjc1209** [comment]
すみません、このチケットはどうやってレビューしますか。

**Comment by yaginuuu** [comment]
@sjc1209 
管理者でログインして試してみてください.

**Comment by sjc1209** [comment]
えっと、管理者のIDとPWDは何ですか。

**Comment by ryoki1118** [comment]
@yaginuuu このチケット今どんな状況なん？

**Comment by sjc1209** [comment]
OKです。
