### ISSUE TITLE
D3.jsライブラリの導入

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#293]
pullrequest #295

**Comment by Altairzym** [comment]
@yaginuuu  @ryoki1118 先週金曜日日立とミーティングの時、D3.jsが認識できなかったと言われて、しかし実際のプロジェクトから見ると
![image](https://cloud.githubusercontent.com/assets/7775369/11201942/f24cd612-8d1d-11e5-844e-dd1114eca8b5.png)
nv.d3.jsもう既に存在している、日立の環境どう再現すればいいでしょう？

**Comment by ryoki1118** [comment]
@Altairzym 存在はしてるけど使ってないってことでしょ？portfolio/index.html.erbのd3.js読み込み部分がインターネット経由になってない？

**Comment by yaginuuu** [comment]
たしかに...ｗ

**Comment by Altairzym** [comment]
@ryoki1118 そうですね、しかしいまindexの中にこんな感じ
![image](https://cloud.githubusercontent.com/assets/7775369/11201990/764ebe76-8d1e-11e5-9f3e-0aa391c989d2.png)特に外から引用していないような気がする

**Comment by yaginuuu** [comment]
@Altairzym 
views/layouts/application.html.erbで読み込んでるんだけど,
includeしてるところをコメントアウトしてみて, グラフ化されるか確認してみてくれる？？

**Comment by ryoki1118** [comment]
@Altairzym そこにd3.jsの読み込み処理は書かれてないね。

**Comment by yaginuuu** [comment]
![image](https://cloud.githubusercontent.com/assets/3440182/11202022/10f9b9e6-8d27-11e5-83e5-d447d3a61eb2.png)

ここ

**Comment by Altairzym** [comment]
@yaginuuu やってみる

**Comment by ryoki1118** [comment]
@yaginuuu それそれ。そこをローカルのd3.jsを読み込むように書き換えましょうー

**Comment by Altairzym** [comment]
@ryoki1118 本当だ。。。

**Comment by Altairzym** [comment]
ここの問題か！

**Comment by yaginuuu** [comment]
書き換えというか、そこをコメントアウトしてグラフ化できれば大丈夫.
JSファイルはすべて読み込みはしてるはずなので。

**Comment by Altairzym** [comment]
@yaginuuu 一応コメントアウトしてみる

**Comment by Altairzym** [comment]
@yaginuuu 確かに、コメントアウトしても実行できる
