### ISSUE TITLE
UbuntuのMysql charset問題

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#298]
- Ubuntuでプロジェクトを登録する時、両方認証しないと、プロジェクト登録が失敗
- 原因：UbuntuでMysqlの設定の方問題があるけど、解決する方法分からない

**Comment by yaginuuu** [comment]
@ryoki1118 
これはローカルのmysqlの文字コードの問題っぽいです.
文字コードがutf-8になってないことが問題なんすけど, 解決方法がわかってない感じです.
