### ISSUE TITLE
コメント量ロジックのBUG

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#299]
### Overview
再現は以下.
- Redmineのテスト環境のproject2、ViBiiのgithubリポジトリ両方と連携する新しいプロジェクトを登録する
- メトリクスを見る画面で、登録したプロジェクトを選択、エラーが出る
![image](https://cloud.githubusercontent.com/assets/7775369/11272314/ee39e624-8f06-11e5-9440-b68c17f15e0e.png)

### DefDone
- 再現のフローを行い, 正常にグラフが表示される

### Test
- [ ] Redmineのsample2を登録し, 正常に登録できる

### PullRequestLink
 #301 

これBUGですw
見つけてくれた @Altairzym ありがとうございます！！

**Comment by yaginuuu** [comment]
@Altairzym 
レビューお願いしまっす.
