### ISSUE TITLE
US01-F01-SP03: システム上のデータベーススキーマを決定する 10.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#3]
## 大木が作成したER図を基にシステム上のスキーマを考えてみました
- 論理モデル
![image](https://cloud.githubusercontent.com/assets/3440182/9489722/ffd09238-4c1d-11e5-8748-1fb1120676ac.png)

- 物理モデル
![image](https://cloud.githubusercontent.com/assets/3440182/9489724/0b93e61a-4c1e-11e5-97bc-d3d3b921c53f.png)

- 変更点, 考慮点
- Active Recordを考慮したスキーマに変更しました
    - 主キーはidで統一した
        - 開発者のアドレスで絞り込みをしてから, idで関連テーブルを取得する
- Railsでの物理モデルにしました
    - テーブル名はスネークケースで記述し, 複数形にする
    - created_at(テーブル作成日時), updated_at(テーブル更新日時)は自動生成される

#103 が実装したものになります！！！！

**Comment by ryoki1118** [comment]
Railsでの実装レベルで決めるのであれば, 柳沼にチケット渡したほうがよい?
概念レベルでのスキーマだったらUS01-F04-SP04でよいかね.

**Comment by yaginuuu** [comment]
@ryoki1118 
なるほどこっちが後か.
おｋコレ俺がやりますー。

**Comment by yaginuuu** [comment]
@ViBii/owners 
システム上のDBスキーマ考えてみましたー。
レビューお願いしますー。

**Comment by ryoki1118** [comment]
現状これでいいけど, 論理モデルがクローズして確定しないとこっちもクローズできないよね...? あと, mitemiruのデータベースにスキーマを登録する作業もあとでお願いします.

**Comment by Altairzym** [comment]
了解です、

**Comment by yaginuuu** [comment]
@ViBii/owners 
こっちも変更しました〜！
レビューお願いしますー。

**Comment by ryoki1118** [comment]
申し訳ない、論理モデル修正しました。
テーブルの作成日時と更新日時も入れてあります。
![mitemiru_db1-1](https://cloud.githubusercontent.com/assets/6702920/9460248/3570b22c-4b3f-11e5-9718-3ad8b2797440.jpg)

ここに保存してあるから使ってもよいよ
"ViBi\00各種ドキュメント\95図\ER図"

**Comment by yaginuuu** [comment]
@ryoki1118 
なるほど…
こっちも修正いたします.

**Comment by yaginuuu** [comment]
@ryoki1118 
subversionのテーブルだけどさ、だれがアップロードしたかっていう(開発者との関連)必要？？

**Comment by ryoki1118** [comment]
誰がっていうか誰のっていう情報。てか.svnファイルの仕様あまり理解していないんだけど、プロジェクト一つに存在する.svnファイルって開発者の数関係なく一つだけ？

**Comment by yaginuuu** [comment]
@ryoki1118 
.gitファイルも.svnファイルも開発者ごとに存在はするけど, mitemiruシステムではプロジェクトごとに設定するから, 俺はプロジェクトごとに1つって考えてた。

**Comment by ryoki1118** [comment]
ほうほう。一つの.svn(.git)ファイルで全情報を取り出せるのであれば、開発者との関連はいらないかな

**Comment by yaginuuu** [comment]
@ryoki1118 
そうだね。
まてよ。。。
これにはシステムのユーザがはいっていない。。。ｗ
システムのユーザもいれないとな。

あと、それにRedmineの認証keyが関連させるのがいいと思う.
そうすると管理権限ごとにまとめられるとおもった。

**Comment by ryoki1118** [comment]
第一スプリントだとシステムのユーザは考慮していないけど、考えてデータベース構築したほうがよい？

**Comment by yaginuuu** [comment]
認証keyをどこに関連付けさせるかだと思う。
チケット管理ツールテーブルに関連して、個人のidとかパスワードとか保持しておくのってなんかアレじゃない？？

**Comment by ryoki1118** [comment]
こういうこと？
![mitemiru_db-1-2](https://cloud.githubusercontent.com/assets/6702920/9464141/6d6e6df0-4b5c-11e5-9b4d-a0f8fa52abb4.jpg)

**Comment by yaginuuu** [comment]
@ryoki1118 
そうそう！
あとはユーザの権限の話は第2スプリント以降にでてきたらカラム追加するってことでいいかなああああ。

**Comment by ryoki1118** [comment]
じゃ論理モデルはこれでいいかな？
返答は「ER図を作成する」のIssueでお願いします。

**Comment by yaginuuu** [comment]
少し修正しましたー。
- ユーザごとにRedmine認証情報を持っておいた方がいいと思うので関連を逆にしました

**Comment by yaginuuu** [comment]
少し修正しましたー。
- Redmine認証情報とチケット管理リポジトリの関連だけど、Redmineを認証したユーザが複数いた時のことを考えれば反対になるのではないかと思った！
![image](https://cloud.githubusercontent.com/assets/3440182/9486703/a0d3515c-4c05-11e5-8993-b3a01cce83e0.png)

**Comment by ryoki1118** [comment]
え、どこが変わった？？
異論はない。

**Comment by yaginuuu** [comment]
@ryoki1118 
チケット管理リポジトリとRemine認証情報の関連だね！
カラムは同じなんだけど、何故か線が反対だった！！

**Comment by ryoki1118** [comment]
おっけ、これでよい。
ER図のほうも修正しときますー

**Comment by yaginuuu** [comment]
@ViBii/owners 
これでDB構築致します！

**Comment by yaginuuu** [comment]
プルリク#103 送りましたー。
レビューよろしく～。

**Comment by yaginuuu** [comment]
@ViBii/owners 
closed致します.
