### ISSUE TITLE
JSの読み込みができていない問題 in heroku

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#302]
### Overview
https://mitemiru.herokuapp.com
heroku上でJSの読み込みができていないため,
- グラフが表示されない
- プロジェクト登録のプロジェクト開始日が変更できない

### Test
- heroku上で確認お願いしまっす.

### PullRequestLink
なし

**Comment by Altairzym** [comment]
@yaginuuu 問題ないです
