### ISSUE TITLE
US03-F01-SP01: Ubuntuのデータベース認証ができない

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#307]
## Overview
Ubuntuでプロジェクトを登録する時、一方のリポジトリだけを登録しようとすると、エラーが出る。原因はMySQLの文字コード設定 ("UTF-8"にしないと動かない)。
確認方法は
$ mysql> show variables like 'character_set%';
<img width="752" alt="2015-12-10 16 42 41" src="https://cloud.githubusercontent.com/assets/6702920/11709700/13352e96-9f5d-11e5-9d83-d2a987bea34c.png">

"character_set_database"と"character_set_server"の文字コードを"UTF-8"にする

## Solution
1. "/etc/mysql/my.cnf"を編集（環境によってインストール先は違います）。見当たらない場合は"/etc/mysql/mysql.conf.d/mysqld.cnf"をコピーする。
2. MySQLが参照している"my.cnf"ファイルに画像の通り, [client]の下に28行目の文, [mysqld]の下に34行目の文を追記。
<img width="752" alt="2015-12-10 16 47 34" src="https://cloud.githubusercontent.com/assets/6702920/11709787/bba41baa-9f5d-11e5-877f-cb0cce6c2b6b.png">
3. MySQLをリスタート
4. 文字コードを確認
画像の通りになっていれば問題なしです。
<img width="752" alt="2015-12-10 16 56 31" src="https://cloud.githubusercontent.com/assets/6702920/11709953/06c50224-9f5f-11e5-80bd-218c4a6c58a5.png">
5. MITEMIRUを起動して登録できるか確認してください。

参考: "http://qiita.com/YusukeHigaki/items/2cab311d2a559a543e3a "

**Comment by ryoki1118** [comment]
@Altairzym @sjc1209 
動作確認してください。

**Comment by ryoki1118** [comment]
@Altairzym 結局解決できてないけど、MITEMIRUのバグではないのでクローズします

**Comment by Altairzym** [comment]
@ryoki1118 おｋ
