### ISSUE TITLE
US02-F01-SP04:UML(ユースケース図, アクティビティ図)の作成 6.0h

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#310]
## Overview
MITEMIRUのユースケース図とアクティビティ図を作成する。

## Done Definition
Taskの完遂後、2人以上のレビューで承認してもらう。
"Dropbox/ViBi/00各種ドキュメント/06UML/"にデータが入っています。

## Task
 - [x] ユースケース図の作成
![default](https://cloud.githubusercontent.com/assets/6702920/11581639/74ea57fe-9a87-11e5-84f1-14b95a5a91b8.png)

 - [x] アクティビティ図の作成(システムユーザ新規登録)
![_](https://cloud.githubusercontent.com/assets/6702920/11618236/6d801d0e-9cdb-11e5-920c-181210475577.png)

 - [x] アクティビティ図の作成(ログイン)
![_](https://cloud.githubusercontent.com/assets/6702920/11618090/cdc2d67c-9cd9-11e5-9621-f8fa88901ada.png)

 - [x] アクティビティ図の作成(ログアウト)
![default](https://cloud.githubusercontent.com/assets/6702920/11582396/b6c80acc-9a91-11e5-9c57-dfbfa6aab76c.png)

 - [x] アクティビティ図の作成(新規プロジェクト登録)
![_](https://cloud.githubusercontent.com/assets/6702920/11618086/c0110c6a-9cd9-11e5-92e6-dd20e3dc1777.png)

 - [x] アクティビティ図の作成(メトリクスデータの閲覧)
![_](https://cloud.githubusercontent.com/assets/6702920/11582003/6df82782-9a8c-11e5-9571-ef2918812cbc.png)

 - [x] アクティビティ図の作成(開発者情報の編集)
![_](https://cloud.githubusercontent.com/assets/6702920/11583804/50147738-9aa1-11e5-8aea-1fcaf5d46252.png)

 - [x] アクティビティ図の作成(開発者情報の削除)
![default](https://cloud.githubusercontent.com/assets/6702920/11583203/9863fa24-9a9a-11e5-902b-decce8a39800.png)

 - [x] アクティビティ図の作成(プロジェクト情報の編集)
![_](https://cloud.githubusercontent.com/assets/6702920/11583793/30879972-9aa1-11e5-9188-a0ff05a0b2bb.png)

 - [x] アクティビティ図の作成(プロジェクト情報の削除)
![_](https://cloud.githubusercontent.com/assets/6702920/11583872/060aa4ae-9aa2-11e5-9b4d-04998a06931b.png)

 - [x] アクティビティ図の作成(リポジトリ認証情報の追加登録)
![_](https://cloud.githubusercontent.com/assets/6702920/11618106/f2556f04-9cd9-11e5-94b4-5b0519175768.png)

 - [x] アクティビティ図の作成(リポジトリ認証情報の編集)
![_](https://cloud.githubusercontent.com/assets/6702920/11618110/037c6a6c-9cda-11e5-8ccf-662add0cb3b9.png)

 - [x] アクティビティ図の作成(システムユーザ情報の編集)
![_](https://cloud.githubusercontent.com/assets/6702920/11584795/659d3b5e-9aaa-11e5-8fba-39ced9be7f10.png)

 - [x] アクティビティ図の作成(システムユーザ情報の削除)
![_](https://cloud.githubusercontent.com/assets/6702920/11584998/ebb8a15a-9aab-11e5-8d03-45db57c29d91.png)

 - [x] アクティビティ図の作成(管理者によるシステムユーザ情報の削除)
![_](https://cloud.githubusercontent.com/assets/6702920/11585006/f39dfec4-9aab-11e5-9afe-6774c50ced92.png)

**Comment by ryoki1118** [comment]
ユースケース図だと思っていた図が、実はアクティビティ図でした。

**Comment by ryoki1118** [comment]
レビューお願いします。

**Comment by ryoki1118** [comment]
すみません、図が1つ抜けてるのでレビュー待ってください。

**Comment by ryoki1118** [comment]
レビューお願いします。

**Comment by sjc1209** [comment]
ユースケース図けど、今のシステム管理者は普通のユーザと同じように、プロジェクトを登録とか、メトリクス見るとか、できますよね。

**Comment by ryoki1118** [comment]
@sjc1209
そうなんだけど、よくよく考えるとユースケースとしてはおかしいよね...
本来であれば使えなくてもいい機能だから省いたんだけど。

**Comment by sjc1209** [comment]
なるほど、

**Comment by sjc1209** [comment]
![image](https://cloud.githubusercontent.com/assets/7754274/11586555/4661d878-9ab7-11e5-928e-2cac8883f9e8.png)

**Comment by sjc1209** [comment]
アクティビティ図の作成(新規プロジェクト登録)のところ、入力されてないじゃなくて、認証ができていないって感じかな。

**Comment by sjc1209** [comment]
すみません、間違いました。大丈夫です。

**Comment by sjc1209** [comment]
アクティビティ図の作成(リポジトリ認証情報の追加登録)のところ、アクセスできない場合、エラーメッセージが表示されるね。

**Comment by sjc1209** [comment]
![image](https://cloud.githubusercontent.com/assets/7754274/11587322/dcbbb0b0-9abb-11e5-9d3e-d322e7e32f91.png)

**Comment by ryoki1118** [comment]
@sjc1209 エラーメッセージの表示追加したので確認してくださーい

**Comment by sjc1209** [comment]
確認しました。OKです。

**Comment by yaginuuu** [comment]
ok!
