### ISSUE TITLE
[IR] US04-F01-SP01: グラフ仕様の設計 8.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#312]
関連事前調査： #261

## グラフの概要

- 対象メトリクス: 専門性
- 利用データ: コミットログ, GitData(Blobs, Commits, Trees)

### 裏側処理
- URL:https://api.github.com/repos/ViBii/mitemiru/commits?author=xxxxx@gmail.com  から、ある開発者の**parents属性の長さは1のcommit**を収集する、そしてsha属性の文字列を洗出して、「コミット番号array」の中の保存する

- 「コミット番号array」をループして、https://api.github.com/repos/ViBii/mitemiru/commits/aae4413aa10520167a741d38c5ef3c0d15557ae5  の様なURLにアクセスする、あるいは、Octokitを利用し、あるコミットの詳細情報を所得する。

- コミットの詳細情報の「files」属性の中の「filename」属性から、編集したファイルの拡張子の名前を「ファイル種類hash」の中に保存する、そして編集回数+1の結果を記録する、「ファイル種類hash」の中にまだ存在してない拡張子の名前があれば、「ファイル種類hash」の中に追加し、回数を記録する(**注意：ここの回数はコミットした回数である。10回コミットすると10回と計算する**)

### JS部分処理

- JSの部分で、裏側の処理のデータをもらってから、各開発者ごとで、各種類のファイルに対する編集した比率を計算して、グラフ上で表示する
  - 比率の計算数式：**ある種類のファイルの編集回数 / 全てのファイルを編集した総回数**

## JSに伝送するデータのイメージ

- 計算したデータの項目
  - 開発者名前array
    - developerNames:[syu,oki,sun,yaginuuu...]
  - 各開発者が編集したファイル拡張子の名前array(**トラッカーのような、一つのarrayに統一したほうがいいか、あるいは個人ごとでarrayを作るどちがいいか、ちょっと分からない**)
    - fileNames:[[js,rb,html,yml...],[js,rb,yml...],[js,html,yml...],[js,rb,html...]]
  - 各開発者がファイル拡張子の名前arrayに対応する編集した回数
    - editCounts:[[22,43,23,12...],[41,11,30...],[50,29,16...],[46,15,34...]]

## 表現手法の提案
- 昨日のミーティングで相談して、以下のことを決定した
  - コミット数グラフと関係なく、新しいグラフを作成する
  - 円グラフで表示すると、棒グラフより見やすい
  - 生産性の様な円グラフと似ている、円のある部分をクリックすると、棒グラフに変更できる
- イメージは以下の図の様な感じ
![image](https://cloud.githubusercontent.com/assets/7775369/11522781/a249322c-98fe-11e5-89bb-3028f58607e7.png)
![image](https://cloud.githubusercontent.com/assets/7775369/11522783/a5618554-98fe-11e5-84ab-0676e26d0901.png)

- もし円のある部分をクリックすると、棒グラフが表示し、棒グラフの中に、チームの中の他の開発者のこの種類のファイルの編集回数を一緒に表示する
![image](https://cloud.githubusercontent.com/assets/7775369/11522800/eaecaa5e-98fe-11e5-8c56-2001f2ac3d89.png)

**Comment by Altairzym** [comment]
@sjc1209 @ryoki1118  レビューお願いします。

**Comment by ryoki1118** [comment]
@Altairzym これってコミット数のグラフとは別で作る事を想定してる？

**Comment by Altairzym** [comment]
@ryoki1118 そうですね。。。

**Comment by Altairzym** [comment]
@mitemiru-reviewer 昨日のミーティングの内容をまとめて、この様な感じに修正しました。どうでしょうか？意見お願いします。

**Comment by sjc1209** [comment]
わかりやすいと思う。いいと思う。ちなみに、＠の人は間違っている。

**Comment by Altairzym** [comment]
@sjc1209 え？その人は？誰？

**Comment by Altairzym** [comment]
@yaginuuu  @ryoki1118  @sjc1209 昨日のミーティングの内容をまとめて、この様な感じに修正しました。どうでしょうか？意見お願いします。

**Comment by sjc1209** [comment]
レビュー専用のアカウントです。

**Comment by ryoki1118** [comment]
@Altairzym グラフ形式の前に、データの集計方法の話も書いてもらえる？そこが抜けてるとこのグラフが適切かどうかの判断ができないかな...

**Comment by Altairzym** [comment]
@ryoki1118  なるほど

**Comment by Altairzym** [comment]
@ryoki1118  @sjc1209 データ取得部分を考えた、どうでしょうか？

**Comment by ryoki1118** [comment]
@Altairzym
データの技術的な収集方法の話じゃなくて、グラフとして表現する数値の集計方法を書いて欲しかった...。データ収集の流れは何となく書いてあるんだけど、結局どんなデータが生成されて、どんな数字として表現されるのかが全くわからないんだよね。

・1つのファイルに10回コミットした場合は、1回としてカウントするのか、それとも10回としてカウントするのか
・開発者ごとに編集ファイルの拡張子をパーセンテージで表現するけど、具体的にはどういう計算で導き出すのか

とりあえずこの辺りがわからないから教えて欲しいかな。

**Comment by Altairzym** [comment]
@ryoki1118 そうだね、確かに。。。修正します

**Comment by Altairzym** [comment]
@ryoki1118  @sjc1209 またよろしくね

**Comment by ryoki1118** [comment]
@Altairzym 
>(注意：ここの回数はコミットした回数である。10回コミットすると10回と計算する)
1回のコミットでfoo.jsとbar.jsを編集した場合は、jsの編集回数はいくつになるの？

**Comment by Altairzym** [comment]
@ryoki1118  実際の例を言うと、以下のURLの集計結果としてはhttps://api.github.com/repos/ViBii/mitemiru/commits/aae4413aa10520167a741d38c5ef3c0d15557ae5
js:2回 rb:1回 html.erb:1回

**Comment by ryoki1118** [comment]
>@ryoki1118 実際の例を言うと、以下のURLの集計結果としてはhttps://api.github.com/repos/ViBii/mitemiru/commits/aae4413aa10520167a741d38c5ef3c0d15557ae5
js:2回 rb:1回 html.erb:1回

この場合、「全てのファイルを編集した総回数」は4回？

**Comment by ryoki1118** [comment]
@Altairzym 
あと別件だけど、他人のブランチをマージした場合ってどうやってカウントするの？
例えばこれとか(孫くんのケース)
https://api.github.com/repos/ViBii/mitemiru/commits?author=yoshisjc113@gmail.com
https://api.github.com/repos/ViBii/mitemiru/commits/ee71d38095407ef708ef1c960c92c0ea774587f9

**Comment by ryoki1118** [comment]
@Altairzym 
#261 にも書いてあるけど、Mergeするとparentsが2つになるから、そこを見て取り除けば適切な回数をカウントできるかも。
<img width="618" alt="2015-12-02 19 20 41" src="https://cloud.githubusercontent.com/assets/6702920/11528420/fb49340a-9929-11e5-9851-8d67b1016412.png">

**Comment by Altairzym** [comment]
@ryoki1118 はい、ありがとう！その部分を参考しながらやります！

**Comment by ryoki1118** [comment]
@Altairzym 
テスト用のブランチで検証した結果(コミット数は4回です)
1. Masterにブランチがマージされるまで、コミットログは取得できない
2. マージすると、今までコミットした人のコミットログに反映される(今回の場合だと4回が大木のコミットとしてログに残る)
https://api.github.com/repos/ViBii/mitemiru/commits?author=r1118oboe@gmail.com
![2015-12-02 19 37 42](https://cloud.githubusercontent.com/assets/6702920/11528795/390246a4-992c-11e5-8a8e-e10b5c32b0a2.png)

3. 2に加えて、Merge pull requestというコミットログが *マージした人のコミットログ* として反映される(今回の場合だと、一民のコミットとしてログが残る)
https://api.github.com/repos/ViBii/mitemiru/commits?author=zouyimin88@gmail.com
![2015-12-02 19 37 42](https://cloud.githubusercontent.com/assets/6702920/11528890/d88d4be2-992c-11e5-9733-64667a2ca50b.png)
今回のケースだと、大木のコミット4回と一民のコミット1回の合計5回がカウントされるようです。

さらに、一民のマージコミットの履歴の詳細を見ると、これまでに俺がコミットした内容が全て含まれています(実際には一民は一度も編集していない)
https://api.github.com/repos/ViBii/mitemiru/commits/16790ad5e883439dd82fb37380e477196d4b74fe
![2015-12-02 19 45 35](https://cloud.githubusercontent.com/assets/6702920/11528988/720ab08e-992d-11e5-8e9b-42bd78a0fb1b.png)

以上の事を踏まえると、マージした時のコミットログを除いた他のコミットログを全て集計すれば、正確な情報を取り出せると思います。

**Comment by ryoki1118** [comment]
@Altairzym ちなみに前述のとおり、マージしたコミットはparents(親ブランチ)が2つになっているので、それを除けばなんとかなると思う

**Comment by Altairzym** [comment]
@ryoki1118 了解です、今この二つのparentsを除くロジックを考えている、ありがとう

**Comment by Altairzym** [comment]
@ryoki1118 記述部分もう修正した、レビューお願い

**Comment by ryoki1118** [comment]
@Altairzym InProgressだけどレビューしていいの？ちなみにどこが変わったの？

**Comment by Altairzym** [comment]
@ryoki1118 「IR」ですよ、レビューお願い！！！！

**Comment by ryoki1118** [comment]
@Altairzym これ実装じゃないでしょ笑
Doneに置いてくださいー

**Comment by Altairzym** [comment]
@ryoki1118 修正箇所は
![image](https://cloud.githubusercontent.com/assets/7775369/11561893/c392b9ca-9a0d-11e5-863c-3609b60c31bc.png)

**Comment by ryoki1118** [comment]
@Altairzym
だいたいおっけーかな
ってもグラフってトラッカーのやつと全く同じってことだよね？笑
何だか変な感じがするんだよなぁ...

**Comment by Altairzym** [comment]
@ryoki1118 そのグラフはエクセルで作成したが、確かに既存のやつと似ている

**Comment by ryoki1118** [comment]
@Altairzym まぁええか。

**Comment by ryoki1118** [comment]
@yaginuuu @sjc1209 レビューよろしくね

**Comment by yaginuuu** [comment]
おｋです.

**Comment by Altairzym** [comment]
closeします
