### ISSUE TITLE
US04-F01-SP02: メトリクスデータ可視化モジュールの実装 4.0h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#316]
## Overview
#312 の実装です。

## Pull Request
#342

**Comment by ryoki1118** [comment]
@Altairzym グラフ作るの？

**Comment by Altairzym** [comment]
@ryoki1118 あ！これ、裏側処理じゃあないね？！！！間違いました！！！

**Comment by yaginuuu** [comment]
@ryoki1118 
@Altairzym 
@sjc1209 
これってクローズしておｋ？
