### ISSUE TITLE
US03-F01-SP05: 開発者の追加登録 #管理機能 3.0h

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#317]
### DefDone
- [x] 認証を追加したら, 新たに開発者を登録する必要がある

### Overview
以下の場合に開発者情報と所属履歴情報を保存します.
- 各種管理画面から認証済みのリポジトリを編集した場合
- 各種管理画面から新しくリポジトリを追加した場合

### Test
- 上記確認お願いします.

### PullRequestLink
#339

**Comment by sjc1209** [comment]
確認しました。OKです。
