### ISSUE TITLE
US04-F01-SP03: メトリクスデータ生成モジュールの実装

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#318]
設計の参考：#312 
pull request：#337

**Comment by ryoki1118** [comment]
@Altairzym Viewに受け渡すデータ一覧と形式書いてもらっていい？

**Comment by Altairzym** [comment]
@ryoki1118 あ、それはもう#312 に書いてあるわ～
![image](https://cloud.githubusercontent.com/assets/7775369/11581620/2f2b94a8-9a87-11e5-8222-62bc3ddcd8e3.png)

**Comment by ryoki1118** [comment]
@Altairzym ちょっとわからないってところはどうなってる？

**Comment by Altairzym** [comment]
@ryoki1118 その部分は、大木君がjs部分を実際に実装する時、どちが便利か相談したい

**Comment by yaginuuu** [comment]
@Altairzym 
これできてるなら、マージしていいです

**Comment by Altairzym** [comment]
@yaginuuu  あ、今まで他のループ方法を考えているけど、まだ新しい案出してない、じゃあマージします
