### ISSUE TITLE
US03-F01-SP06: プロジェクト一覧におけるリポジトリ認証情報 が間違っている問題 3.0h

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#319]
### DefDone
- [x] BUGが修正されている

### Overview
プロジェクト一覧画面において, 「認証済み」ボタンを押した時, 表示する認証情報が間違っている.

1. プロジェクト情報は以下のように登録する
![_20151116152915](https://cloud.githubusercontent.com/assets/7754274/11175630/9b92f1d6-8c77-11e5-80ab-0e19df78bbb0.png)

2. プロジェクト一覧画面において, 「認証済み」ボタンを押した時, 間違っている情報が表示される
![_20151116152946](https://cloud.githubusercontent.com/assets/7754274/11175645/c2d1419e-8c77-11e5-8ad0-9c42613322db.png)

### Test
- 修正されているかどうか確認

### PullRequestLink
#332

**Comment by sjc1209** [comment]
![image](https://cloud.githubusercontent.com/assets/7754274/11522340/8166798e-98f9-11e5-80b8-26e5799baa21.png)
![image](https://cloud.githubusercontent.com/assets/7754274/11522350/96cfd036-98f9-11e5-8d33-685808c9a00e.png)
![image](https://cloud.githubusercontent.com/assets/7754274/11522358/aae1f5b8-98f9-11e5-9768-6428f3e40b36.png)

**Comment by sjc1209** [comment]
今このような情報を登録したけど、認証情報がまた間違っている。

**Comment by yaginuuu** [comment]
@sjc1209 
これ検証したいんで、テストユーザのIDとパスワード教えて下さいー

**Comment by sjc1209** [comment]
ID：sun
PWD：yosjc113

**Comment by yaginuuu** [comment]
@sjc1209 
この問題も仕様ですね。
リポジトリはユニークに登録されているので、同じシステムユーザで同じリポジトリに対して違う認証情報で認証を行った場合、その判別はできないです。
このような状況は対象外だと思います。

**Comment by sjc1209** [comment]
えっと、例えば私たち4人が所属しているRedmineのプロジェクトで、つまり、同じプロジェクトに所属している開発者が複数がいるが、そのプロジェクトに対し、管理者は一人だけはずですか。システムユーザ、つまり、プロジェクトの管理者が認証情報を登録する時、同じ認証情報が唯一のログインIDはずですね。

**Comment by yaginuuu** [comment]
んーそうですね。
だから、問題ないと思います。

**Comment by sjc1209** [comment]
なるほど、じゃOKです。

**Comment by yaginuuu** [comment]
>リダイレクトの話だけど、飛ばされた先で「プロジェクトが未登録なので登録してください」みたいな文章出して欲しいかも。じゃないとバグだと思われるかも。
