### ISSUE TITLE
RedmineリポジトリのURLのNULLチェックがない 2.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#324]
## Overview
プロジェクト登録でGitHubのリポジトリだけ認証しようとした場合、RedmineのURLのパターンチェックでエラーがでる(NULLのチェックがない)

入力例:
![2015-11-26 14 38 08](https://cloud.githubusercontent.com/assets/6702920/11415879/c43589d8-944b-11e5-9d35-0ba22a197f66.png)

出力エラー:
![2015-11-26 14 37 53](https://cloud.githubusercontent.com/assets/6702920/11415883/d10c7590-944b-11e5-902b-0b7f4a0ce096.png)

### PullRequestLink
#332

**Comment by ryoki1118** [comment]
@yaginuuu 対応求む

**Comment by sjc1209** [comment]
これはまたできていないですね。同じ問題発生している。

**Comment by yaginuuu** [comment]
まだレビュー依頼してないっすｗ

**Comment by sjc1209** [comment]
doneにしたので、もう完成したと思った。

**Comment by yaginuuu** [comment]
@sjc1209 
修正しました〜。
確認して欲しいです〜。

**Comment by sjc1209** [comment]
確認しました。OKです。
