### ISSUE TITLE
プロジェクト登録する時、Githubの認証情報のチェック問題

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#325]
![image](https://cloud.githubusercontent.com/assets/7754274/11417025/7be1bcb4-9456-11e5-97fe-6894cb22ead8.png)
![image](https://cloud.githubusercontent.com/assets/7754274/11417031/88b4627a-9456-11e5-93d6-9dd0e442f10f.png)
Githubのプロジェクトに所属してないユーザでも、認証ができている。
多分GithubのログインIDとGithub上のプロジェクトのチェックが漏れた。

**Comment by yaginuuu** [comment]
@sjc1209 
これってどういうことですか？？

**Comment by ryoki1118** [comment]
@sjc1209 @yaginuuu これってこの前に話してた、リポジトリのContributorじゃなくても認証が通るって話だよね？結局のところ、仕様上は問題ないってことでいいのかな...？

**Comment by yaginuuu** [comment]
あーあの話かああ。
仕様ってことでいいと思います！

**Comment by ryoki1118** [comment]
@sjc1209 @yaginuuu 公開リポジトリなら全く問題ないね！未公開リポジトリの場合は対策必要だけど。

**Comment by yaginuuu** [comment]
@ryoki1118 
@sjc1209 
未公開リポジトリの時の対策はしてあるので, 大丈夫です！API認証弾かれるかどうかのロジックは書いてますー

**Comment by sjc1209** [comment]
なるほど、じゃこのチケットをcloseしますか。

**Comment by ryoki1118** [comment]
これはCloseしましょう
