### ISSUE TITLE
ホーム画面でプロジェクトが登録されてない場合、メッセージを表示する 1.0h

### ISSUE THREAD

**Issue by sjc1209** [ViBii/mitemiru#329]
### DefDone
- [x] BUGが修正されている

### Overview
- プロジェクトが登録されていない場合, プロジェクト登録画面にリダイレクトされるように変更しました.

### Test
- BUGが修正されているかどうか確認

### PullRequestLink
#332

**Comment by sjc1209** [comment]
プロジェクトが登録されていない場合, プロジェクト登録画面にリダイレクトされるように変更しました.

これはできているけど、MITEMIRUのlogoクリックする時、ホームページのURL、つまり、http://localhost:3000に移動するはずが、またhttp://localhost:3000/projects/newです。また、「メトリクスを見る」ボタンを押すとき、またプロジェクトの登録画面が表示されている。
![image](https://cloud.githubusercontent.com/assets/7754274/11522501/f352123c-98fa-11e5-9eda-a6fce8e1722d.png)

**Comment by yaginuuu** [comment]
@sjc1209 
そういう風に変更したんです。
どこかBUGありますか？

**Comment by sjc1209** [comment]
なるほど、つまり、プロジェクトが登録しないと、メトリクスを見る機能は無効ですね。
でも、少なくとも、システムのホームページのURLは変わることはないね。MITEMIRUのlogoを押すと、URLはhttp://localhost:3000で、画面はプロジェクトの登録画面はずだと思う。

**Comment by yaginuuu** [comment]
ん？？
なにが正解なのかわからないですー

**Comment by sjc1209** [comment]
システムのホームページはhttp://localhost:3000だということは変わらないことだと思う。今MITEMIRUのlogoクリックして、移動先はずのホームページはhttp://localhost:3000/projects/newになった。つまり、まだプロジェクトが登録してない状態だと、システムのホームページがないです。これはよくないね。

**Comment by yaginuuu** [comment]
>リダイレクトの話だけど、飛ばされた先で「プロジェクトが未登録なので登録してください」みたいな文章出して欲しいかも。じゃないとバグだと思われるかも。

**Comment by sjc1209** [comment]
「まずはじめにプロジェクト登録しましょう 」って文法的に正しいですか。wordで貼り付けると、「重ね言葉」って言われた。

**Comment by yaginuuu** [comment]
ｗｗｗｗ

**Comment by yaginuuu** [comment]
日本語の文法を修正される日本人ｗｗｗ
どのように書けばよろしいでしょうか？？ｗｗｗ

**Comment by sjc1209** [comment]
いえいえ、確認したいだけです。「まずはプロジェクトを登録しましょう 」ってどうですか。

**Comment by yaginuuu** [comment]
「プロジェクト登録して下さい」にしますか？無難に。

**Comment by sjc1209** [comment]
はい、いいと思います。

**Comment by sjc1209** [comment]
確認しました。OKです。
