### ISSUE TITLE
US01-F03-SP01: テストツールを決定, 導入する

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#5]
## やったこと
#55

**Comment by yaginuuu** [comment]
レビューお願いしますー。

**Comment by Altairzym** [comment]
さすがです！！！！！っていいですか？

**Comment by yaginuuu** [comment]
@Altairzym いいですか？ってなにー？？ｗ

**Comment by Altairzym** [comment]
「さすがです！！！！！」と言うレビューのコメント。。。

**Comment by yaginuuu** [comment]
おｋ！

**Comment by sjc1209** [comment]
最後記述したところ、CIツールも導入したいって、これはやるべきことですか、あるいは未定ですか。未定の場合はこのチケットが終わったって言えますか。

**Comment by yaginuuu** [comment]
このチケットですが, テストツールは導入できています.
なので, テストする分には問題ありません.
CIツールを導入する時はまた違うチケットを作ろうと思います！

**Comment by sjc1209** [comment]
わかりました。じゃOKです。

**Comment by Altairzym** [comment]
OKです！

**Comment by ryoki1118** [comment]
ちなみにみんなpullして動かしてるよね？
