### ISSUE TITLE
構成, チケット管理ツールの認証方法

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#56]
開発者が取り組んだプロジェクト情報を構成・チケット管理ツールから取得するために行う認証方法はどうするのか.

問題点: 他者の認証情報を利用できない
開発者の秘密鍵やユーザ情報（ID, パスワード等）をプロジェクト管理者が利用して, 構成・チケット管理ツールにアクセスすることはできない（なりすましによる不正アクセスと同義？）.

対策:
1. 構成・チケット管理ツールに対して, プロジェクト管理者のアクセス権（アカウント）を発行し, 情報を取得する.
2. 開発者が構成・チケット管理ツールから必要な情報を予め静的ファイルとして出力し, それを利用する.

上記のとおり, 認証方法が決まらないとデータベースの設計ができません.

**Comment by yaginuuu** [comment]
プロジェクト管理者も開発者と同じ権限を持っている前提だったよね？？
開発者が構成・チケット管理ツールから取得する情報はプロジェクト管理者も認証できるという風に考えていた.

**Comment by ryoki1118** [comment]
> プロジェクト管理者も開発者と同じ権限を持っている前提だったよね？？
そう思ってたんだけど, ドキュメントとしてどこにも記載がなかったから確認しておきたかった. プロジェクト管理者がアクセス権持ってるってことで進めときますー.

**Comment by yaginuuu** [comment]
![image](https://cloud.githubusercontent.com/assets/3440182/9410209/e7cfff42-4859-11e5-98e6-d67d7690b974.png)
システムのスキーマとしては, 構成管理ツール・チケット管理ツールというテーブルはいらないと思うけど(多分, 外部のDBの話だよね？？)それ以外はおｋだと思うー。

**Comment by ryoki1118** [comment]
あー, 「チケット管理ツール」と「構成管理ツール」のテーブルは, 内部のデータベースのつもり. GitとかSubversionとかツール名保持しとこうとか考えてたけど, 実際必要ないかもね. また書き換えてあげときます. とりあえずこのIssueはクローズしときます.

**Comment by Altairzym** [comment]
すみませんが、この図を見ると、分析するデータはどこで保存されているですか？

**Comment by ryoki1118** [comment]
分析データの保存はしてないね。
その話はUS01-F04-SP04でやります。
このIssueはクローズします。
