### ISSUE TITLE
システムの機能確認

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#57]
システム構成図を書くために, 改めて機能を整理したのでコメントください.
よければこれを参考に構成図描きます.

1. 基本機能
     - プロジェクトの一覧表示
     - プロジェクトの概要表示
     - メトリクスの表示
     - 情報の外部出力
     - 情報のソート・検索（フィルタリング）
     - メモ機能

2. ポートフォリオ機能
     - 成長過程の閲覧
（複数プロジェクト間のメトリクス比較）
     
3. 開発者の比較機能
     - 開発者間のメトリクス比較（1人の開発者につき, 1つのプロジェクト）

4. 情報の登録・管理
     - 構成・チケット管理ツールの認証情報
     - 開発者情報
     - プロジェクト情報

**Comment by yaginuuu** [comment]
@ryoki1118 
これでいいと思います。

**Comment by Altairzym** [comment]
了解です。修正します。
