### ISSUE TITLE
US01-F01-SP01: プレ環境を整える 2.0h+4.0h 

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#59]
### Doneの定義
- [x] CIツール導入
    - <a href='http://wercker.com/'>wercer</a>を採用
- [x] slackにビルド結果を通知
    - ci_alermというチャンネル
- [x] 自動デプロイ
    - herokuにプレ環境を構築

### HowTo
1. 各ブランチにpushするとwerckerが起動
2. masterが更新された段階でherokuへデプロイ

### プルリクのリンク
#158

### テスト
- [x] 上記の手順でheroku上でauto-deployブランチが反映されている
- [x] 他のメンバーが上記を確認できる

**Comment by yaginuuu** [comment]
@ViBii/owners 
レビューお願いします！
このブランチをcheckoutして、
app/views/base/top.html.erbを編集して、
以下で反映されるのが確認できれば成功です.
https://mitemiru.herokuapp.com

**Comment by ryoki1118** [comment]
追記してみたけど更新されない！

**Comment by yaginuuu** [comment]
@ryoki1118 
ごめん！
masterに取り込んでもらえればデプロイされるようにしてあった！
なので誰かマージボタンを！！！

**Comment by sjc1209** [comment]
すみません、どのブランチですか。

**Comment by yaginuuu** [comment]
@sjc1209 
上に説明してあります…

**Comment by sjc1209** [comment]
![qq 20150909171830](https://cloud.githubusercontent.com/assets/7754274/9756682/128d64a6-5717-11e5-9cf2-cbb8f883b330.png)

**Comment by sjc1209** [comment]
こんな感じでいいですか。

**Comment by yaginuuu** [comment]
@sjc1209 
はいー。
大木がもう追加してたからマージボタンを押してくれるだけでよかったです！
お願いします！

**Comment by sjc1209** [comment]
わかりました。

**Comment by yaginuuu** [comment]
うわーなんか変なファイル追加されたｗｗｗｗ

**Comment by yaginuuu** [comment]
@sjc1209 自分のcommit確認しよう…

**Comment by sjc1209** [comment]
お！どうやって削除しますか。まずローカルで削除するか

**Comment by yaginuuu** [comment]
@sjc1209 
ブランチ名を変更してプルリクを出して欲しかったですが、今回はこれでいいです。
プルリクをだしてみてください。
あと、自分の開発ブランチにpushするときはもちろんですが、他の人のブランチにpushするときはより自分のcommit内容を意識してください。

**Comment by yaginuuu** [comment]
@sjc1209 
@Altairzym 
(こうやってレビューする人を指名するのがいいかも！)
![image](https://cloud.githubusercontent.com/assets/3440182/9757412/73982692-571b-11e5-9389-aec0eef5c7ac.png)

上記のように大木と孫くんのコミットが反映されているので、自動デプロイできてることが確認されました。

**Comment by sjc1209** [comment]
はい、わかりました。
OKです。

**Comment by yaginuuu** [comment]
@ryoki1118 
でも追記してくれたの大木なんで、やっぱレビューお願いしますｗ

**Comment by ryoki1118** [comment]
masterに直接追記はできないから確認はできないけど、Merge後に更新が反映されているみたいだからよいよ

**Comment by yaginuuu** [comment]
はい。closedしますー。
