### ISSUE TITLE
US01-F03-SP02: Ruby, Rails, ライブラリの利用バージョンを決定する

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#6]

**Comment by ryoki1118** [comment]
詳細
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/07%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83
