### ISSUE TITLE
仕様の変更に合わせて、チケットを変更する 3.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#62]
US01, US02の決定に伴い、US03, US04およびUS08を変更します。
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/05%E7%AC%AC%E4%B8%80%E3%82%B9%E3%83%97%E3%83%AA%E3%83%B3%E3%83%88%E3%83%90%E3%83%83%E3%82%AF%E3%83%AD%E3%82%B0

**Comment by sjc1209** [comment]
後は、Redmineにチケットを更新する必要がありますね。

**Comment by yaginuuu** [comment]
@sjc1209 
そうね。それ孫くんにやってもらおうかな

**Comment by sjc1209** [comment]
はい、わかりました。変更した内容はUS４とUS８ですよね。
やらねばならないことはRedmineの優先度のところに「高め」にしますか。

**Comment by yaginuuu** [comment]
@sjc1209 
普通でいいよ。

**Comment by sjc1209** [comment]
はい、わかりました。

**Comment by yaginuuu** [comment]
@ryoki1118 
このissueはclosedしてもいいと思います！

**Comment by ryoki1118** [comment]
@sjc1209 US03もね。

**Comment by sjc1209** [comment]
はい、わかりました。
