### ISSUE TITLE
US08-F01_1-SP02: 構成管理ツールの構成ファイル参照先情報をデータベースに登録する 13.0h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#66]
#107

**Comment by yaginuuu** [comment]
構成管理ツール情報(コミット情報)、DBに保存した方がいい気がした。
csvファイルの内容をアップロードしたらDBに保存されるようにしていいですか？
また新しいテーブル作るってことになりますｗ

**Comment by ryoki1118** [comment]
問題ないと思うー

**Comment by yaginuuu** [comment]
りょ！

**Comment by ryoki1118** [comment]
見積もり8.0ptくらいでもいいと思う

**Comment by yaginuuu** [comment]
@ryoki1118 
変更するのはよくないよなｗ

**Comment by ryoki1118** [comment]
このチケットさ、構成管理ファイルのリンク先をデータベースに登録するって意味だった。笑

**Comment by yaginuuu** [comment]
あーそうだった！ｗ

**Comment by yaginuuu** [comment]
@ViBii/owners 
ちょっと説明長くなったけど、プルリク見てくださいー :+1:
