### ISSUE TITLE
US01-F03-SP03: 開発手順(Github, Redmine)を決定する 2.5h

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#7]
## やったこと
- Redmineにまとめた
    - [x] チケット開発フローについて
    - [x] 実装フローについて  

http://vibi-redmine.herokuapp.com/projects/vibi/wiki/01%E9%96%8B%E7%99%BA%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8

**Comment by yaginuuu** [comment]
レビュお願い致しますー。

**Comment by Altairzym** [comment]
了解です、問題ないと思う

**Comment by ryoki1118** [comment]
GitHub-Frowの話だけど, 疑問点二つありますー
1. ブランチのネーミングルールはどうする？
2. マージ許可は誰が出す？

**Comment by ryoki1118** [comment]
あとZenHubのIsuueにも作業時間記載するんだっけ？

**Comment by yaginuuu** [comment]
@ryoki1118 
ブランチのネーミングは意味があるものであればおｋにしよー。
例: issue番号とか開発する内容とか

マージ許可もチケット同様, レビュが2人以上おｋだったらマージしようー。

**Comment by yaginuuu** [comment]
時間は俺が忘れちゃいそうだから書いてるだけー。

**Comment by ryoki1118** [comment]
じゃブランチとマージの話もWikiに書いておいて。
そしたらCloseでいいと思います
