### ISSUE TITLE
US08-F02-SP01_1: 構成管理ツールの構成ファイルから開発者情報を取得し, 一覧表示する

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#75]
構成管理ツールからはcommitしたdevelper, commit情報しか取得できそうにもないから、チケット管理ツールから取得して欲しい！

**Comment by yaginuuu** [comment]
>US08-F02-SP01_1: 構成管理ツールの構成ファイルから開発者情報を取得し, 一覧表示する

なんだけど、構成管理ツールからはcommitしたdevelperしか取得できないから、チケット管理ツールから取得して欲しい！

**Comment by ryoki1118** [comment]
上記理由により、削除しました。 [5.0pt]
