### ISSUE TITLE
US01-F03-SP05: コーディング規約を決定する

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#8]
## やったこと
- [x] HTML, CSS, JavaScript, Rubyに関してのコーディング規約を作成

以下参照
http://vibi-redmine.herokuapp.com/projects/vibi/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84

**Comment by yaginuuu** [comment]
レビューお願いしますー。

**Comment by sjc1209** [comment]
ひとつ疑問ですが、どうしてCSSはIDにはスタイルを適応しないですか。

**Comment by yaginuuu** [comment]
@sjc1209 
idは基本的にDOM操作に使用するので, スタイルはclassのみで行って欲しいです.

**Comment by yaginuuu** [comment]
http://neareal.com/1569/

**Comment by sjc1209** [comment]
なるほど。わかりました。OKです。

**Comment by ryoki1118** [comment]
これでいいと思う。
問題が出てきたらまたその時に話し合おう

**Comment by Altairzym** [comment]
問題ないと思います。
