### ISSUE TITLE
D3.jsの研修 4.0h

### ISSUE THREAD

**Issue by Altairzym** [ViBii/mitemiru#86]
### ToDo
- [x] ウェブサイト:http://dotinstall.com/lessons/basic_d3js
から、全17回のビデオを見る
- [x] 自分でサンプルプロジェクトを作る
- [x] helloTeamViBiにpushする

**Comment by yaginuuu** [comment]
@Altairzym 
どれくらいでいけるかなー.
3min × 17 = 約1.0hくらいだね.
見積もり1とかにしとくか？

**Comment by Altairzym** [comment]
一応ToDoListの中の作業が完了した。
学習した時作ったサンプルは全部helloViBiTeamのにプッシュした。

**Comment by ryoki1118** [comment]
終わったならCloseしていいと思うよ

**Comment by yaginuuu** [comment]
closedしていいと思います！
