### ISSUE TITLE
US01-F03-SP07: 開発環境を作成する(大木)

### ISSUE THREAD

**Issue by yaginuuu** [ViBii/mitemiru#9]

**Comment by ryoki1118** [comment]
<img width="617" alt="2015-08-18 21 37 42" src="https://cloud.githubusercontent.com/assets/6702920/9330044/7a39b398-45f1-11e5-9e0f-0536bedc28d8.png">

**Comment by ryoki1118** [comment]
上記のとおりです

**Comment by yaginuuu** [comment]
おｋ

**Comment by Altairzym** [comment]
問題ない！
