### ISSUE TITLE
US08-F04-SP03: 開発者のプロジェクト所属情報登録フォームを作成する 1h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#92]
## ToDo
- [x] コントローラとルーティングの設定
- [x] 新規画面表示できる
- [x] 入力フォームの中の開発者とプロジェクトのプルダウンリストの作成

 #124　です
一応こんな感じになった
![image](https://cloud.githubusercontent.com/assets/7775369/9575186/7134887e-5008-11e5-85bf-d27b878e8b52.png)

**Comment by Altairzym** [comment]
このissueについて、開発者とプロジェクトは画面でどんな感じでひょうじしますか？プルダウンリストから選択しますか？

**Comment by ryoki1118** [comment]
プルダウンリストで選択かなー

**Comment by ryoki1118** [comment]
mergeしたらクローズしていいよ

**Comment by Altairzym** [comment]
了解です！
