### ISSUE TITLE
US04-F02-SP02: チケットの担当者ごとにトラッカーを分類し, グラフ化して表示する 3.5h

### ISSUE THREAD

**Issue by ryoki1118** [ViBii/mitemiru#98]
## Done definition.
 - トラッカーのグラフ化処理のうち、Viewを作成する。(#192)

## What I did.
#192 参照

**Comment by yaginuuu** [comment]
@ryoki1118 
このチケットってRedmineから直接のデータだよね？？
まだdoneには出来ないって感じ？？

**Comment by ryoki1118** [comment]
@yaginuuu Viewはできた状態だね。#97 でRedmineの情報を取ってくることにはなってるけど、controllerの処理とViewを統合しなきゃいけないね。

**Comment by ryoki1118** [comment]
@yaginuuu Viewができたってことで終了にはしたいけどどうなんだろ。

**Comment by yaginuuu** [comment]
@ryoki1118 
なるほど、Doneの定義明確ならおｋだと思います〜

**Comment by ryoki1118** [comment]
@yaginuuu クローズして問題ないってこと？

**Comment by yaginuuu** [comment]
:+1:
